(in-package :image-agent/cli)
(defstruct (chat (:constructor %make-chat)) controller model key base-url transport
  (history nil) on-tool on-context (tool-limit 20) context-limit
  (context-tokens 65536) compact-threshold (output-reserve 8192)
  (count-support :unknown) (compact-support :unknown) (calibration 1)
  (compactions 0) (backend "none") (counting "estimated") (input-tokens 0)
  (seen (make-hash-table :test 'equal)))
(defun make-chat (controller &key (model (image-agent::environment "OPENAI_MODEL"))
                                  (key (image-agent::api-key))
                                  (base-url (or (image-agent::environment "OPENAI_BASE_URL") "https://api.openai.com/v1"))
                                  (transport #'image-agent::default-transport) on-tool on-context
                                  (tool-limit 20) context-limit (context-tokens 65536) compact-threshold)
  (unless (and (stringp model) (plusp (length model)) (stringp key) (plusp (length key))
               (integerp tool-limit) (plusp tool-limit)
               (or (null context-limit) (and (integerp context-limit) (>= context-limit 16384))))
    (error 'image-agent:configuration-error :message "Set OPENAI_MODEL and API credentials; tool limit must be positive"))
  (multiple-value-bind (threshold reserve) (validate-context-settings context-tokens compact-threshold)
    (%make-chat :controller controller :model model :key key :base-url base-url :transport transport
                :tool-limit tool-limit :context-limit context-limit :on-tool on-tool :on-context on-context
                :context-tokens context-tokens :compact-threshold threshold :output-reserve reserve)))
(defun completed-response (text)
  "Use only the authoritative completed output, never partial argument deltas."
  (unless (and (stringp text) (<= (length text) 1048576)) (error "Response exceeds limit"))
  (let ((data nil) (response nil) (finished-items nil) (text-output (make-string-output-stream)))
    (labels ((dispatch ()
               (when data
                 (when response (error "Data after completion"))
                 (let* ((event (parse-json (format nil "~{~a~^~%~}" (nreverse data)) 1048576))
                        (type (gethash "type" event)))
                   (cond ((equal type "response.output_item.done")
                          (let ((item (gethash "item" event)))
                            (unless (hash-table-p item) (error "Invalid completed item"))
                            (push item finished-items)))
                         ((equal type "response.output_text.delta")
                          (write-string (gethash "delta" event) text-output))
                         ((equal type "response.completed")
                          (let ((r (gethash "response" event)))
                            (unless (and (hash-table-p r) (equal (gethash "status" r) "completed")
                                         (vectorp (gethash "output" r)) (not (stringp (gethash "output" r)))
                                         (every #'hash-table-p (gethash "output" r))) (error "Incomplete response"))
                            (setf response r)))
                         ((member type '("error" "response.failed") :test #'equal)
                          (let ((detail (or (gethash "error" event)
                                            (gethash "error" (or (gethash "response" event) (object))) event)))
                            (error 'image-agent::responses-error :kind
                                   (if (and (hash-table-p detail)
                                            (equal (gethash "code" detail) "context_length_exceeded"))
                                       :context-overflow :failed))))
                         ((member type '("response.incomplete"
                                         "response.refusal.delta" "response.refusal.done") :test #'equal)
                          (error "Failed response"))))
                 (setf data nil))))
      (with-input-from-string (s text)
        (loop for raw = (read-line s nil nil) while raw
              for line = (string-right-trim '(#\Return) raw) do
          (cond ((zerop (length line)) (dispatch))
                ((and (>= (length line) 5) (string= line "data:" :end1 5))
                 (push (string-left-trim '(#\Space) (subseq line 5)) data)))))
      (when (or data (null response)) (error "Missing completed response")))
    ;; Underclass completes with an empty output array; its output_item.done records
    ;; hold the full calls. They are eligible only after response.completed.
    (when (zerop (length (gethash "output" response)))
      (let ((items (nreverse finished-items)) (text (get-output-stream-string text-output)))
        (when (and (plusp (length text))
                   (not (find "message" items :key (lambda (item) (gethash "type" item)) :test #'equal)))
          (setf items (append items (list (object "type" "message" "role" "assistant" "content"
                                                  (vector (object "type" "output_text" "text" text)))))))
        (setf (gethash "output" response) (coerce items 'vector))))
    response))
(defun message (role text) (object "role" role "content" text))
(defun response-text (output)
  (with-output-to-string (s)
    (loop for item across output when (equal (gethash "type" item) "message") do
      (loop for part across (gethash "content" item) do
        (when (equal (gethash "type" part) "output_text") (write-string (gethash "text" part) s))))))
(defun chat-instructions (chat)
  (format nil "You operate a loaded Common Lisp world through registered tools. Inspect available functions and describe them as needed. Use develop_form to add, redefine, or remove functionality. In the reference adapter remove a local managed function with (fmakunbound 'name), optionally in PROGN with requested caller repairs. Before removal inspect relevant catalogue sources and report identifiable callers; references are advisory because computed calls cannot be reliably detected. Keep callers unless the user requests repairs or removal; never cascade deletion automatically. Accepted removal is reversible through revision rollback. Use execute_form to run existing functionality or nested Lisp compositions, preview=false for normal execution, preview=true only for explicit managed-state previews. Reuse existing functions; do not define a named composition unless the user requests reusable functionality. Safe code/data changes create revisions; pure execution and no-ops do not. Preview restores managed resources, not arbitrary external effects. Ordinary execution retains successful managed changes. Observe before editing; never refer to IMAGE-AGENT, IMAGE-AGENT/CLI, or IMAGE-AGENT/EXPERIMENTS symbols. Goals and safety invariants belong to the caller. A paused frame retains live restarts across prompts; repairs are provisional until resumed. Accepted revisions persist, but observation generations are temporary concurrency tokens, NOT revision numbers. Roll back only when the user explicitly requests it; list revisions to resolve the target, clarify ambiguity, and call rollback_revision with a revision ID or number. Rollback unwinds any paused attempt and publishes a new revision; old stacks cannot be restored. Use conversation summaries to retain user goals, constraints, decisions, and facts. Summaries are fallible; fresh worker state and tool results take precedence for application state, revisions, checks, and restart IDs. Do not claim a change succeeded unless tool results establish it. Stop after fulfilling the request. Current state: ~a. Recent accepted revisions: ~a."
          (json (chat-world-context chat))
          (json (subseq (history-json (chat-controller chat)) 0
                        (min 8 (length (history-json (chat-controller chat))))))))
(defun chat-turn (chat text)
  (unless (and (stringp text) (plusp (length text)) (<= (length text) 16384))
    (error "Provide 1 to 16384 characters"))
  (setf (chat-history chat) (append (chat-history chat) (list (message "user" text))))
  (let ((calls-used 0) (seen (chat-seen chat)) (overflow-retried nil))
    (dolist (item (chat-history chat))
      (when (equal (gethash "type" item) "function_call")
        (setf (gethash (gethash "call_id" item) seen) t)))
    (loop
      (unless (ensure-chat-context chat)
        (return "Context compaction failed; conversation and live world are preserved. Retry /compact or inspect /context."))
      (let* ((body (json (chat-request chat (chat-history chat))))
             (response (handler-case
                           (completed-response (chat-transport-request chat "/responses" body))
                         (image-agent::responses-error (c)
                           (if (and (eq (image-agent::responses-error-kind c) :context-overflow)
                                    (not overflow-retried))
                               (progn
                                 (setf overflow-retried t)
                                 (unless (nth-value 1 (compact-chat chat))
                                   (return-from chat-turn "Context compaction failed; conversation and live world are preserved. Retry /compact or inspect /context."))
                                 nil)
                               (return-from chat-turn "OpenAI request failed; no partial tool call was executed. You can retry.")))
                         (error ()
                           ;; The request may have had side effects at the provider, but local tools did not run.
                           (return-from chat-turn "OpenAI request failed; no partial tool call was executed. You can retry."))))
             (output (and response (gethash "output" response)))
             (calls (remove-if-not (lambda (item) (equal (gethash "type" item) "function_call")) (coerce output 'list))))
        (when response
          (record-chat-usage chat response)
          ;; Validate all call identities before retaining or executing this response.
          (unless (and (<= (length calls) 1)
                       (every (lambda (call)
                                (let ((id (gethash "call_id" call)))
                                  (and (stringp id) (plusp (length id)) (not (gethash id seen))
                                       (stringp (gethash "name" call)) (stringp (gethash "arguments" call))))) calls))
            (return "Invalid tool-call response; no tools were executed."))
          (setf (chat-history chat) (append (chat-history chat) (coerce output 'list)))
          (unless calls
            (notify-chat-context chat "usage")
            (let ((text (response-text output)))
              (return (if (plusp (length text)) text "OpenAI returned no text or tool calls."))))
          (dolist (call calls)
            (let* ((id (gethash "call_id" call))
                   (result (if (>= calls-used (chat-tool-limit chat))
                               (object "error" "Tool budget exhausted; no action executed")
                               (handler-case
                                   (progn (incf calls-used)
                                          (dispatch-tool (controller-tools (chat-controller chat))
                                                         (gethash "name" call) (parse-json (gethash "arguments" call))))
                                 (error () (object "error" "Tool failed or arguments invalid; inspect current state before retrying"))))))
              (handler-case (json result)
                (error () (setf result (object "error" "Tool result could not be encoded; inspect current state"))))
              (setf (gethash id seen) t)
              (setf (chat-history chat)
                    (append (chat-history chat)
                            (list (object "type" "function_call_output" "call_id" id "output" (json result)))))
              (when (chat-on-tool chat)
                (handler-case (funcall (chat-on-tool chat) (gethash "name" call) result)
                  (error () nil)))))
          (notify-chat-context chat "usage")
          (when (or (>= calls-used (chat-tool-limit chat)) (terminal-p (controller-view (chat-controller chat))))
            (return (format nil "Tool loop stopped (~d calls). Current state: ~a" calls-used
                            (json (view-json (controller-view (chat-controller chat))))))))))))
