(in-package :image-agent/cli)
(defun demo-adapter ()
  (let* ((world (image-agent:make-reference-world :initial '((:x . 0))))
         (form (image-agent:parse-one-form "(defun counter () (gethash :x *state* 0))" (image-agent:world-package world))))
    (eval form) (funcall (image-agent:world-record-form world) form)
    (list :id "demo" :world world
          :invariants (list (cons :nonnegative-counter
                                 (lambda () (let ((x (gethash :x (image-agent:reference-table world))))
                                              (and (integerp x) (>= x 0)))))))))
(defun adapter (file)
  (if file
      (let ((*package* (find-package :cl-user)))
        (load file :verbose nil :print nil)
        (let ((symbol (find-symbol "MAKE-CLI-WORLD" :cl-user)))
          (unless (and symbol (fboundp symbol)) (error "Program must define CL-USER:MAKE-CLI-WORLD"))
          (funcall symbol)))
      (demo-adapter)))
(defun ensure-workspace (store id)
  (unless (and (stringp id) (plusp (length id))
               (every (lambda (c) (or (alphanumericp c) (find c "-_"))) id))
    (error "Adapter :id must use letters, digits, hyphens, or underscores"))
  (let* ((root (image-agent::directory-path store)) (file (merge-pathnames "workspace.sexp" root)))
    (ensure-directories-exist file)
    (if (probe-file file)
        (unless (equal id (getf (image-agent::read-record file) :adapter-id))
          (error "This workspace belongs to another adapter; choose --store"))
        (progn (image-agent::write-durable file (list :adapter-id id))
               (image-agent::sync-directory root)))))
(defun print-view (controller &optional (stream *standard-output*))
  (let* ((v (controller-view controller))
         (records (image-agent:list-revisions (image-agent:session-store (controller-session controller)))))
    (format stream "~&~a | revision ~a (~a) | generation ~a | budget ~a~%"
            (getf v :status) (getf (first records) :sequence) (getf v :revision)
            (getf v :generation) (getf v :remaining))
    (format stream "~a~%" (getf v :observation))
    (when (getf v :outcome) (format stream "~s~%" (getf v :outcome)))
    (when (getf v :goals) (format stream "Goals: ~s~%" (getf v :goals)))
    (when (getf v :invariants) (format stream "Safety: ~s~%" (getf v :invariants)))
    (when (getf v :condition) (format stream "Condition: ~a~%" (getf v :condition)))
    (dolist (r (getf v :restarts))
      (format stream "Restart ~a (~a): ~a~%" (getf r :id) (getf r :name) (getf r :report)))))
(defun read-form-source (first-line package input output)
  (let ((source first-line))
    (loop
      (handler-case
          (progn (image-agent:parse-one-form source package) (return source))
        (end-of-file ()
          (when (> (length source) 16384) (error "Form exceeds 16384 characters"))
          (write-string "... " output) (finish-output output)
          (let ((line (read-line input nil nil)))
            (unless line (return-from read-form-source nil))
            (setf source (format nil "~a~%~a" source line))))))))
(defun help-text ()
  (format nil "Chat is ordinary text. /mode lisp submits one form (multiline supported).~%/help  /status  /history  /rollback ID|NUMBER|previous~%/model [NAME]  /mode chat|lisp  /chat TEXT  /eval FORM  /abort  /quit~%Use chat to ask OpenAI to resume a displayed restart, or to repair a paused call.~%"))
(defun repl (controller &key model (tool-limit 20) (input *standard-input*) (output *standard-output*) chat-factory)
  (let ((mode "chat") (chat nil))
    (labels ((invoke (action &rest fields)
               (apply #'controller-action controller
                      (object "generation" (getf (controller-view controller) :generation)) action fields)
               (print-view controller output))
             (ask (text)
               (unless chat
                 (setf chat (if chat-factory (funcall chat-factory controller model)
                                (make-chat controller :model model :tool-limit tool-limit
                                  :on-tool (lambda (name result)
                                             (format output "~&tool ~a: ~a~%" name
                                                     (or (and (hash-table-p result) (gethash "error" result))
                                                         (and (hash-table-p result) (gethash "outcome" result)) "done"))
                                             (finish-output output))))))
               (format output "~&~a~%" (chat-turn chat text))
               (print-view controller output)))
      (format output "~&Live Lisp image REPL. Program loaded. /help for commands.~%")
      (print-view controller output)
      (loop
        (format output "~&~a> " mode) (finish-output output)
        (let ((line (read-line input nil nil)))
          (unless line (return))
          (handler-case
              (let ((text (string-trim '(#\Space #\Tab #\Return) line)))
                (unless (zerop (length text))
                  (if (char= (char text 0) #\/)
                      (let* ((split (position-if (lambda (c) (find c '(#\Space #\Tab))) text))
                             (command (subseq text 0 split))
                             (argument (if split (string-trim '(#\Space #\Tab) (subseq text split)) "")))
                        (cond ((equal command "/quit") (return))
                              ((equal command "/help") (write-string (help-text) output))
                              ((equal command "/status") (print-view controller output))
                              ((equal command "/history")
                               (loop for record across (history-json controller) do
                                 (format output "~a  ~a  parent=~a rollback-source=~a~%"
                                         (gethash "number" record) (gethash "id" record)
                                         (gethash "parent" record) (gethash "rollback_source" record))))
                              ((equal command "/mode")
                               (unless (member argument '("chat" "lisp") :test #'equal) (error "Use /mode chat or /mode lisp"))
                               (setf mode argument))
                              ((equal command "/model")
                               (when (plusp (length argument))
                                 (setf model argument)
                                 (when chat (setf (chat-model chat) model (chat-history chat) nil)))
                               (format output "Model: ~a~%" (or model "not configured; set /model NAME")))
                              ((equal command "/chat") (ask argument))
                              ((equal command "/eval")
                               (let ((source (read-form-source argument
                                              (image-agent:world-package (image-agent:session-world (controller-session controller))) input output)))
                                 (unless source (return))
                                 (invoke :evaluate :source source)))
                              ((equal command "/abort") (invoke :abort))
                              ((equal command "/rollback") (invoke :rollback :revision argument))
                              (t (error "Unknown command; use /help"))))
                      (if (equal mode "chat") (ask text)
                          (let ((source (read-form-source line
                                         (image-agent:world-package (image-agent:session-world (controller-session controller))) input output)))
                            (unless source (return))
                            (invoke :evaluate :source source))))))
            (image-agent:configuration-error ()
              (format output "Chat requires OPENAI_MODEL plus OPENAI_API_KEY or OPENAI_API_KEY_FILE (or local Underclass configuration).~%"))
            (error () (format output "Command failed. Use /help or /status; Lisp forms must contain exactly one form.~%"))))))))
(defun parse-options (arguments)
  (let ((options nil))
    (loop while arguments for name = (pop arguments) do
      (when (equal name "--help") (return-from parse-options (list :help t)))
      (unless (member name '("--program" "--store" "--model" "--budget" "--tool-limit") :test #'equal)
        (error "Unknown option"))
      (unless arguments (error "Option needs a value"))
      (let ((value (pop arguments)))
        (setf (getf options (intern (string-upcase (subseq name 2)) :keyword))
              (if (member name '("--budget" "--tool-limit") :test #'equal)
                  (let ((n (parse-integer value))) (unless (plusp n) (error "Budget must be positive")) n)
                  value))))
    options))
;; Linux/SBCL is the supported deployment. A process lock prevents two CLIs publishing the same store.
(sb-alien:define-alien-routine ("flock" workspace-flock) sb-alien:int (fd sb-alien:int) (operation sb-alien:int))
(defun main (arguments)
  (let* ((options (parse-options arguments)))
    (when (getf options :help)
      (format t "image-repl [--program FILE] [--store DIR] [--model NAME] [--budget 1000] [--tool-limit 20]~%~a" (help-text))
      (return-from main nil))
    (let* ((spec (adapter (getf options :program))) (id (getf spec :id))
           (world (getf spec :world))
           (store (or (getf options :store) (format nil ".image-agent/workspaces/~a/" id)))
           (lock-path (merge-pathnames "workspace.lock" (image-agent::directory-path store))))
      (unless (typep world 'image-agent::world) (error "Adapter must supply :world"))
      (ensure-directories-exist lock-path)
      (with-open-file (lock lock-path :direction :output :if-exists :append :if-does-not-exist :create)
        (unless (zerop (workspace-flock (sb-sys:fd-stream-fd lock) 6))
          (error "Workspace is already open in another CLI"))
        (ensure-workspace store id)
        (let ((session (apply (if (image-agent::current-revision store) #'image-agent:recover-session #'image-agent:make-session)
                              world (append (if (image-agent::current-revision store) (list store) (list :store store))
                                            (list :interactive t :goals (getf spec :goals) :invariants (getf spec :invariants)
                                                  :budget (or (getf options :budget) 1000))))))
          (unwind-protect
               (repl (make-controller session)
                     :model (or (getf options :model) (image-agent::environment "OPENAI_MODEL"))
                     :tool-limit (or (getf options :tool-limit) 20))
            (image-agent:close-session session)))))))

(sb-ext:lock-package :image-agent/cli)
