(in-package :image-agent/cli)
(defun demo-adapter ()
  (let* ((world (image-agent:make-reference-world :initial '((:x . 0))))
         (form (image-agent:parse-one-form "(defun counter () (gethash :x *state* 0))" (image-agent:world-package world))))
    (image-agent:validate-form form)
    (funcall (image-agent:world-validate-form world) form)
    (eval form) (funcall (image-agent:world-record-form world) form)
    (list :id "demo" :world world
          :invariants (list (cons :nonnegative-counter
                                 (lambda () (let ((x (gethash :x (image-agent:reference-table world))))
                                              (and (integerp x) (>= x 0)))))))))
(defun adapter (file)
  (if file
      (let ((*package* (find-package :cl-user)))
        (load file :verbose nil :print nil)
        (let ((symbol (find-symbol "MAKE-CLI-WORLD" :cl-user)))
          (unless (and symbol (fboundp symbol)) (error "Program must define CL-USER:MAKE-CLI-WORLD"))
          (funcall symbol)))
      (demo-adapter)))
(defun ensure-workspace (store id)
  (unless (and (stringp id) (plusp (length id))
               (every (lambda (c) (or (alphanumericp c) (find c "-_"))) id))
    (error "Adapter :id must use letters, digits, hyphens, or underscores"))
  (let* ((root (image-agent::directory-path store)) (file (merge-pathnames "workspace.sexp" root)))
    (ensure-directories-exist file)
    (if (probe-file file)
        (unless (equal id (getf (image-agent::read-record file) :adapter-id))
          (error "This workspace belongs to another adapter; choose --store"))
        (progn (image-agent::write-durable file (list :adapter-id id))
               (image-agent::sync-directory root)))))
(defun print-view (controller &optional (stream *standard-output*))
  (let* ((v (controller-view controller))
         (records (image-agent:list-revisions (image-agent:session-store (controller-session controller)))))
    (format stream "~&~a | revision ~a (~a) | generation ~a | budget ~a~%"
            (getf v :status) (getf (first records) :sequence) (getf v :revision)
            (getf v :generation) (getf v :remaining))
    (format stream "~a~%" (getf v :observation))
    (when (getf v :outcome) (format stream "~s~%" (getf v :outcome)))
    (when (getf v :goals) (format stream "Goals: ~s~%" (getf v :goals)))
    (when (getf v :invariants) (format stream "Safety: ~s~%" (getf v :invariants)))
    (when (getf v :condition) (format stream "Condition: ~a~%" (getf v :condition)))
    (dolist (r (getf v :restarts))
      (format stream "Restart ~a (~a): ~a~%" (getf r :id) (getf r :name) (getf r :report)))))
(defun read-form-source (first-line package input output &key reader)
  (let ((source first-line))
    (loop
      (handler-case
          (progn (image-agent:parse-one-form source package) (return source))
        (end-of-file ()
          (when (> (length source) 16384) (error "Form exceeds 16384 characters"))
          (if reader
              (let ((next (funcall reader source)))
                (unless next (return-from read-form-source nil)) (setf source next))
              (progn (write-string "... " output) (finish-output output)
                     (let ((line (read-line input nil nil)))
                       (unless line (return-from read-form-source nil))
                       (setf source (format nil "~a~%~a" source line))))))))))
(defparameter +repl-commands+
  '(("/help" "" "Show commands and editing keys")
    ("/mode" "chat|lisp" "Switch between prompting and Lisp")
    ("/status" "" "Inspect worker state, checks, and live restarts")
    ("/history" "" "List accepted application revisions")
    ("/operations" "" "List recent attempts and outcomes")
    ("/functions" "[OFFSET]" "Discover available functions")
    ("/describe" "NAME" "Inspect arguments, documentation, and source")
    ("/develop" "FORM" "Add or redefine functionality")
    ("/execute" "FORM" "Execute existing functionality")
    ("/preview" "FORM" "Execute and restore managed state")
    ("/chat" "TEXT" "Send a prompt from either mode")
    ("/model" "[NAME]" "Inspect or select the model")
    ("/compact" "" "Compact conversation memory and preserve the live worker")
    ("/context" "[clear]" "Show context usage or explicitly forget conversation memory")
    ("/rollback" "ID|NUMBER|previous" "Restore a revision and preserve history")
    ("/abort" "" "Abort a paused attempt and restore its checkpoint")
    ("/quit" "" "Close the application worker")))
(defun command-help-json ()
  (coerce (mapcar (lambda (entry) (object "command" (first entry) "arguments" (second entry)
                                          "description" (third entry))) +repl-commands+) 'vector))
(defun help-text ()
  (format nil "Chat is ordinary text. Lisp forms may span lines.~%~{~a~%~}~%Interactive editing: arrows edit and recall whole submissions; Enter submits complete input; Alt+Enter inserts a newline; Ctrl+C clears input; Ctrl+D exits an empty buffer.~%Input history is saved per workspace. /history lists application revisions.~%Use /abort to unwind a paused attempt. Preview restores managed effects only.~%"
          (mapcar (lambda (entry) (format nil "~a ~a  ~a" (first entry) (second entry) (third entry))) +repl-commands+)))
(defun repl (controller &key model (tool-limit 20) (context-tokens 65536) compact-threshold
                            (input *standard-input*) (output *standard-output*)
                            chat-factory submission-reader presenter)
  (let ((mode "chat") (chat nil) (current-command nil))
    (labels ((present (kind data plain)
               (if presenter (funcall presenter kind data) (funcall plain)))
             (show-view (&optional detail)
               (present :view (object "view" (view-json (controller-view controller)) "detail" (if detail 'yason:true 'yason:false)
                                     "command" current-command)
                        (lambda () (print-view controller output))))
             (read-submission (&optional (continuation nil) initial)
               (if submission-reader
                   (funcall submission-reader (if continuation "lisp" mode) continuation initial
                            (image-agent:world-package (image-agent:session-world (controller-session controller))))
                   (progn (format output "~&~a> " mode) (finish-output output) (read-line input nil nil))))
             (form-source (source)
               (read-form-source source (image-agent:world-package (image-agent:session-world (controller-session controller)))
                                 input output :reader (and submission-reader
                                   (lambda (initial) (read-submission t initial)))))
             (invoke (action &rest fields)
               (apply #'controller-action controller
                      (object "generation" (getf (controller-view controller) :generation)) action fields)
               (show-view))
             (show-context (data)
               (present :context data
                        (lambda ()
                          (let ((phase (gethash "phase" data)))
                            (unless (equal phase "usage")
                              (format output "~&Context: ~a; ~d/~d tokens (estimated), threshold ~d; ~d compactions; backend ~a.~%"
                                      (or phase "status") (gethash "input_tokens" data)
                                      (gethash "context_tokens" data) (gethash "compact_threshold" data)
                                      (gethash "compactions" data) (gethash "backend" data))
                              (when (and (null phase) (plusp (or (gethash "last_request_tokens" data) 0)))
                                (format output "Last request: ~d tokens (~a).~%"
                                        (gethash "last_request_tokens" data) (gethash "last_request_counting" data)))
                              (finish-output output))))))
             (ensure-chat ()
               (unless chat
                 (setf chat (if chat-factory (funcall chat-factory controller model)
                                (make-chat controller :model model :tool-limit tool-limit
                                  :context-tokens context-tokens :compact-threshold compact-threshold
                                  :on-tool (lambda (name result)
                                             (present :tool (object "name" name "result" result)
                                                      (lambda ()
                                                        (format output "~&tool ~a: ~a~%" name
                                                                (or (and (hash-table-p result) (gethash "error" result))
                                                                    (and (hash-table-p result) (gethash "outcome" result)) "done"))
                                                        (finish-output output)))))))
                 (setf (chat-on-context chat) #'show-context))
               chat)
             (ask (text)
               (present :busy (object "text" "Asking the model") (lambda () nil))
               (ensure-chat)
               (let ((reply (chat-turn chat text)))
                 (present :assistant (object "text" reply) (lambda () (format output "~&~a~%" reply))))
               (show-view)))
      (unless presenter (format output "~&Live Lisp image REPL. Program loaded. /help for commands.~%"))
      (show-view)
      (loop
        (let ((line (read-submission)))
          (unless line (return))
          (handler-case
              (let ((text (string-trim '(#\Space #\Tab #\Return #\Newline) line)))
                (unless (zerop (length text))
                  (setf current-command nil)
                  (if (char= (char text 0) #\/)
                      (let* ((split (position-if (lambda (c) (find c '(#\Space #\Tab #\Return #\Newline))) text))
                             (command (subseq text 0 split))
                             (argument (if split (string-trim '(#\Space #\Tab #\Return #\Newline) (subseq text split)) "")))
                        (setf current-command command)
                        (cond ((equal command "/quit") (return))
                              ((equal command "/help")
                               (present :help (object "text" (help-text) "commands" (command-help-json))
                                        (lambda () (write-string (help-text) output))))
                              ((equal command "/status") (show-view t))
                              ((equal command "/history")
                               (present :history (object "revisions" (history-json controller))
                                        (lambda () (loop for record across (history-json controller) do
                                          (format output "~a  ~a  parent=~a rollback-source=~a~%"
                                                  (gethash "number" record) (gethash "id" record)
                                                  (gethash "parent" record) (gethash "rollback_source" record))))))
                              ((equal command "/mode")
                               (unless (member argument '("chat" "lisp") :test #'equal) (error "Use /mode chat or /mode lisp"))
                               (setf mode argument)
                               (present :mode (object "mode" mode) (lambda () nil)))
                              ((equal command "/model")
                               (when (plusp (length argument))
                                 (setf model argument)
                                 (when chat (setf (chat-model chat) model) (clear-chat-context chat)))
                               (present :model (object "model" model)
                                        (lambda () (format output "Model: ~a~%" (or model "not configured; set /model NAME")))))
                              ((equal command "/chat") (ask argument))
                              ((equal command "/context")
                               (unless (member argument '("" "clear") :test #'equal) (error "Use /context [clear]"))
                               (cond ((and chat (equal argument "clear")) (clear-chat-context chat))
                                     (chat (show-context (chat-context-status chat)))
                                     (t (present :context
                                          (object "phase" "empty" "input_tokens" 0 "counting" "estimated"
                                                  "context_tokens" context-tokens
                                                  "compact_threshold" (or compact-threshold (floor (* context-tokens 7) 10))
                                                  "compactions" 0 "backend" "none")
                                          (lambda () (format output "No conversation memory yet. Context window: ~d tokens.~%" context-tokens))))))
                              ((equal command "/compact")
                               (unless (zerop (length argument)) (error "Use /compact"))
                               (if (and chat (chat-history chat))
                                   (progn (present :busy (object "text" "Compacting conversation") (lambda () nil))
                                          (compact-chat chat))
                                   (present :diagnostic (object "text" "No conversation memory to compact.")
                                            (lambda () (format output "No conversation memory to compact.~%")))))
                              ((member command '("/develop" "/execute" "/preview") :test #'equal)
                               (let ((source (form-source argument)))
                                 (unless source (return))
                                 (invoke (if (equal command "/develop") :develop :execute) :source source :preview (equal command "/preview"))))
                              ((equal command "/functions")
                               (let ((offset (if (plusp (length argument)) (parse-integer argument) 0)))
                                 (unless (>= offset 0) (error "Offset must be nonnegative"))
                                 (invoke :inspect :offset offset)))
                              ((equal command "/describe") (invoke :describe :name argument))
                              ((equal command "/operations") (invoke :operations))
                              ((equal command "/abort") (invoke :abort))
                              ((equal command "/rollback") (invoke :rollback :revision argument))
                              (t (error "Unknown command; use /help"))))
                      (if (equal mode "chat") (ask text)
                          (let ((source (form-source line)))
                            (unless source (return))
                            (invoke :execute :source source :preview nil))))))
            (image-agent:configuration-error ()
              (present :error (object "text" "Chat requires OPENAI_MODEL plus OPENAI_API_KEY or OPENAI_API_KEY_FILE (or local Underclass configuration).")
                       (lambda () (format output "Chat requires OPENAI_MODEL plus OPENAI_API_KEY or OPENAI_API_KEY_FILE (or local Underclass configuration).~%"))))
            (error ()
              (present :error (object "text" "Command failed. Use /help or /status; Lisp forms must contain exactly one form.")
                       (lambda () (format output "Command failed. Use /help or /status; Lisp forms must contain exactly one form.~%")))))))
      (present :exit (object "text" "Application closed. Accepted changes are saved.") (lambda () nil)))))
(defun parse-options (arguments)
  (let ((options nil))
    (loop while arguments for name = (pop arguments) do
      (when (equal name "--help") (return-from parse-options (list :help t)))
      (unless (member name '("--program" "--store" "--model" "--budget" "--tool-limit"
                            "--context-tokens" "--compact-threshold") :test #'equal)
        (error "Unknown option"))
      (unless arguments (error "Option needs a value"))
      (let ((value (pop arguments)))
        (setf (getf options (intern (string-upcase (subseq name 2)) :keyword))
              (if (member name '("--budget" "--tool-limit" "--context-tokens" "--compact-threshold") :test #'equal)
                  (let ((n (parse-integer value))) (unless (plusp n) (error "Budget must be positive")) n)
                  value))))
    (validate-context-settings (or (getf options :context-tokens) 65536) (getf options :compact-threshold))
    options))
;; Linux/SBCL is the supported deployment. A process lock prevents two CLIs publishing the same store.
(sb-alien:define-alien-routine ("flock" workspace-flock) sb-alien:int (fd sb-alien:int) (operation sb-alien:int))
(defun main (arguments &key submission-reader presenter)
  (let* ((options (parse-options arguments)))
    (when (getf options :help)
      (format t "image-repl [--program FILE] [--store DIR] [--model NAME] [--budget 1000] [--tool-limit 20] [--context-tokens 65536] [--compact-threshold TOKENS] [--plain] [--no-emoji]~%~a" (help-text))
      (return-from main nil))
    (let* ((spec (adapter (getf options :program))) (id (getf spec :id))
           (world (getf spec :world))
           (store (or (getf options :store) (format nil ".image-agent/workspaces/~a/" id)))
           (recovered (image-agent::current-revision store))
           (lock-path (merge-pathnames "workspace.lock" (image-agent::directory-path store))))
      (unless (typep world 'image-agent::world) (error "Adapter must supply :world"))
      (ensure-directories-exist lock-path)
      (with-open-file (lock lock-path :direction :output :if-exists :append :if-does-not-exist :create)
        (unless (zerop (workspace-flock (sb-sys:fd-stream-fd lock) 6))
          (error "Workspace is already open in another CLI"))
        (ensure-workspace store id)
        (let ((session (apply (if (image-agent::current-revision store) #'image-agent:recover-session #'image-agent:make-session)
                              world (append (if (image-agent::current-revision store) (list store) (list :store store))
                                            (list :interactive t :goals (getf spec :goals) :invariants (getf spec :invariants)
                                                  :budget (or (getf options :budget) 1000))))))
          (unwind-protect
               (progn
                 (when presenter
                   (funcall presenter :startup (object "application" id "workspace" (namestring (truename (image-agent::directory-path store)))
                     "model" (or (getf options :model) (image-agent::environment "OPENAI_MODEL"))
                     "recovered" (if recovered 'yason:true 'yason:false) "commands" (command-help-json))))
                 (repl (make-controller session)
                       :model (or (getf options :model) (image-agent::environment "OPENAI_MODEL"))
                       :tool-limit (or (getf options :tool-limit) 20)
                       :context-tokens (or (getf options :context-tokens) 65536)
                       :compact-threshold (getf options :compact-threshold)
                       :submission-reader submission-reader :presenter presenter))
            (image-agent:close-session session)))))))

(sb-ext:lock-package :image-agent/cli)
