;;;; Opt-in bounded evolution of existing managed numeric functions.
;;;; No general evaluator, remote calls, mutable judges, publication or defaults.
;;;; Receipts are trusted local managed data, not cryptographic authorization.
(defmodule jiti_evolution
  (export (generate 5) (propose 8) (inspect 1) (promote 1)))

(defun require (ok) (if ok 'ok (error 'invalid_proposal)))
(defun between (n lo hi) (andalso (is_integer n) (>= n lo) (=< n hi)))
(defun digest (term)
  (binary:encode_hex (crypto:hash 'sha256 (term_to_binary term '(deterministic)))))
(defun key (id)
  (require (andalso (is_binary id) (> (byte_size id) 0) (=< (byte_size id) 64)))
  (tuple 'jiti_evolution id))
(defun snapshot ()
  (let ((s (get 'jiti_candidate))) (require (is_map s)) s))
(defun fingerprint (s)
  (digest (list (map-get s 'definitions) (map-get s 'state)
                (maps:get 'catalogue s (map)))))
(defun rejected (reason) (map 'status 'rejected 'reason reason))
(defun guarded (task)
  (try (funcall task) (catch ((tuple _ _ _) (rejected 'invalid_proposal)))))

;; Only small integer constants, argument references and binary +, -, *.
;; Counting consumes a shared budget: branching cannot evade the node limit.
(defun expression (e args depth budget)
  (require (andalso (> budget 0) (=< depth 8)))
  (cond
    ((is_integer e) (require (between e -1000000 1000000)) (- budget 1))
    ((is_atom e) (require (lists:member e args)) (- budget 1))
    ('true
     (let (((list op a b) e))
       (require (lists:member op '(+ - *)))
       (expression b args (+ depth 1)
         (expression a args (+ depth 1) (- budget 1)))))))
(defun definition (ast arity)
  (let (((list 'lambda args body) ast))
    (require (andalso (is_list args) (=:= (length args) arity)
                     (=:= (length (lists:usort args)) arity)
                     (lists:all (fun is_atom 1) args)))
    (expression body args 1 63)
    ast))
(defun baseline (name arity)
  (require (andalso (is_atom name) (between arity 1 4)))
  (require (not (lists:member name '(+ - * lambda quote state-get state-put state-delete forget))))
  (let ((defs (map-get (snapshot) 'definitions)))
    ;; A managed arithmetic shadow would diverge from the fixed DSL evaluator.
    (require (not (lists:any (lambda (k) (lists:member (element 1 k) '(+ - *)))
                             (maps:keys defs))))
    (definition (map-get defs (tuple name arity)) arity)))
(defun options (opts)
  (require (is_map opts))
  (require (=:= (lists:sort (maps:keys opts))
                (lists:sort '(seed population generations timeout_ms))))
  (require (between (map-get opts 'seed) 0 2147483646))
  (require (between (map-get opts 'population) 1 32))
  (require (between (map-get opts 'generations) 1 8))
  (require (=< (* (map-get opts 'population) (map-get opts 'generations)) 64))
  (require (between (map-get opts 'timeout_ms) 0 250))
  opts)

;; Stable LCG and preorder point mutation; each generation descends from the
;; previous candidate, not heldout feedback. All attempts count against bounds.
(defun next-seed (seed) (rem (+ (* seed 1103515245) 12345) 2147483647))
(defun node-count
  (((list _ a b)) (+ 1 (node-count a) (node-count b)))
  ((_) 1))
(defun mutate (expr index delta)
  (if (=:= index 0)
      (if (is_integer expr) (+ expr delta) (list '+ expr delta))
      (let* (((list op a b) expr) (size (node-count a)))
        (if (=< index size)
            (list op (mutate a (- index 1) delta) b)
            (list op a (mutate b (- index size 1) delta))))))
(defun variants
  ((0 _ _ _ acc) (lists:reverse acc))
  ((count ast arity seed acc)
   (let* (((list 'lambda args expr) ast)
          (s (next-seed seed))
          (delta (lists:nth (+ 1 (rem s 4)) '(-2 -1 1 2)))
          (candidate (list 'lambda args (mutate expr (rem (div s 4) (node-count expr)) delta)))
          (valid (try (definition candidate arity) (catch ((tuple _ _ _) ast)))))
     (variants (- count 1) valid arity s (cons valid acc)))))
(defun generate (name arity seed population generations)
  (options (map 'seed seed 'population population 'generations generations 'timeout_ms 100))
  (let ((base (baseline name arity)))
    (lists:delete base (lists:usort (variants (* population generations) base arity seed ())))))

(defun fixtures (rows arity safety)
  (require (andalso (is_list rows) (> (length rows) 0) (=< (length rows) 32)))
  (lists:foreach
    (lambda (row)
      (require (=:= (length row) (if safety 3 2)))
      (let ((args (car row)))
        (require (andalso (is_list args) (=:= (length args) arity)
                         (lists:all (lambda (n) (between n -1000000 1000000)) args))))
      (require (lists:all (lambda (n) (between n -1000000000 1000000000)) (cdr row)))
      (if safety (require (=< (cadr row) (caddr row))) 'ok)) rows)
  (require (=:= (length rows) (length (lists:usort (lists:map (fun car 1) rows)))))
  rows)
(defun inputs-disjoint (train heldout)
  (require (not (lists:any
    (lambda (r) (lists:keymember (car r) 1 (lists:map (fun list_to_tuple 1) heldout))) train))))
(defun value (expr env)
  (let ((result
          (cond
            ((is_integer expr) expr)
            ((is_atom expr) (map-get env expr))
            ('true
             (let* (((list op a b) expr) (x (value a env)) (y (value b env)))
               (case op ('+ (+ x y)) ('- (- x y)) ('* (* x y))))))))
    (require (between result -1000000000 1000000000))
    result))
(defun dsl-call (ast args)
  (let (((list 'lambda vars body) ast)) (value body (maps:from_list (lists:zip vars args)))))
(defun loss (ast rows)
  (lists:sum (lists:map (lambda (r) (abs (- (dsl-call ast (car r)) (cadr r)))) rows)))
(defun safe (ast rows)
  (lists:all (lambda (r)
    (let ((v (dsl-call ast (car r)))) (andalso (>= v (cadr r)) (=< v (caddr r))))) rows))
(defun measurement (ast train heldout safety)
  (map 'hash (digest ast) 'ast ast 'train (loss ast train)
       'heldout (loss ast heldout) 'safe (safe ast safety)))
(defun score (base candidates train heldout safety)
  (let* ((before (measurement base train heldout safety))
         (results (lists:map (lambda (ast) (measurement ast train heldout safety)) candidates))
         (best (lists:min (lists:map (lambda (m) (map-get m 'train)) results)))
         (winners (lists:filter (lambda (m) (=:= (map-get m 'train) best)) results))
         (common (map 'baseline before 'measurements results)))
    ;; Never search/rerank using heldout or safety measurements.
    (maps:merge common
      (cond
        ((not (map-get before 'safe)) (rejected 'baseline_unsafe))
        ((/= (length winners) 1) (rejected 'tie))
        ((>= best (map-get before 'train)) (rejected 'no_improvement))
        ('true
         (let ((winner (car winners)))
           (cond
             ((not (map-get winner 'safe)) (rejected 'safety_failed))
             ((>= (map-get winner 'heldout) (map-get before 'heldout)) (rejected 'heldout_failed))
             ('true (map 'status 'ready 'winner winner)))))))))
(defun bounded (task timeout)
  (if (=:= timeout 0) (rejected 'timeout)
    (let* ((parent (self)) (tag (make_ref))
           ((tuple pid monitor)
            (spawn_opt (lambda () (! parent (tuple tag (guarded task)))) '(link monitor))))
      ;; Linking ensures outer controller timeouts also kill this evaluator.
      (receive
        ((tuple tag result) (unlink pid) (erlang:demonitor monitor '(flush)) result)
        (after timeout
          (unlink pid) (exit pid 'kill)
          (receive ((tuple 'DOWN monitor 'process pid _) 'ok))
          (receive ((tuple tag _) 'ok) (after 0 'ok))
          (rejected 'timeout))))))
(defun request-score (base candidates train heldout safety arity opts)
  (options opts)
  (require (andalso (is_list candidates) (> (length candidates) 0)
                   (=< (length candidates) (* (map-get opts 'population) (map-get opts 'generations)))
                   (=:= (length candidates) (length (lists:usort candidates)))))
  (lists:foreach (lambda (ast) (definition ast arity)) candidates)
  (fixtures train arity 'false) (fixtures heldout arity 'false) (fixtures safety arity 'true)
  (inputs-disjoint train heldout)
  (bounded (lambda () (score base candidates train heldout safety)) (map-get opts 'timeout_ms)))

;; A proposal writes only its unique receipt key. Promotion must be the next
;; publication after this receipt: any intervening publication requires reproposal.
(defun propose (id name arity candidates train heldout safety opts)
  (guarded (lambda ()
    (let* ((k (key id)) (s (snapshot)) (base (baseline name arity))
           (_ (require (not (maps:is_key k (map-get s 'state)))))
           (_ (options opts))
           (pool (if (=:= candidates 'generate)
                     (generate name arity (map-get opts 'seed) (map-get opts 'population)
                               (map-get opts 'generations)) candidates))
           (result (request-score base pool train heldout safety arity opts))
           (receipt (map-set result 'version 1 'id id 'target (tuple name arity)
                     'base_revision (map-get s 'revision) 'base_hash (digest base)
                     'snapshot_hash (fingerprint s) 'candidates pool 'train train
                     'heldout heldout 'safety safety 'options opts)))
      (jiti_kernel:state-put k (map-set receipt 'digest (digest receipt)))))))
(defun inspect (id) (jiti_kernel:state-get (key id)))
(defun promote (id)
  (guarded (lambda ()
    (let* ((k (key id)) (s (snapshot)) (r (inspect id))
           (_ (require (=:= (map-get r 'digest) (digest (maps:remove 'digest r)))))
           (_ (require (=:= (map-get r 'version) 1)))
           ((tuple name arity) (map-get r 'target))
           (base (baseline name arity))
           (without (map-set s 'state (maps:remove k (map-get s 'state)))))
      (cond
        ((orelse (/= (map-get s 'parent) (map-get r 'base_revision))
                 (=< (map-get s 'revision) (map-get r 'base_revision))
                 (/= (fingerprint without) (map-get r 'snapshot_hash))
                 (/= (digest base) (map-get r 'base_hash))) (rejected 'stale_baseline))
        ((/= (map-get r 'status) 'ready) (rejected 'proposal_not_ready))
        ('true
         (let ((fresh (request-score base (map-get r 'candidates) (map-get r 'train)
                        (map-get r 'heldout) (map-get r 'safety) arity (map-get r 'options))))
           (if (andalso (=:= (map-get fresh 'status) 'ready)
                        (=:= (map-get fresh 'winner) (map-get r 'winner))
                        (=:= (map-get fresh 'baseline) (map-get r 'baseline))
                        (=:= (map-get fresh 'measurements) (map-get r 'measurements)))
               (progn
                 ;; Only the targeted definition changes; normal kernel safety,
                 ;; controller publication, goals, history and rollback still run.
                 (put 'jiti_candidate
                   (map-set s 'definitions (map-set (map-get s 'definitions)
                       (tuple name arity) (map-get (map-get fresh 'winner) 'ast))))
                 (map-set fresh 'status 'promoted 'proposal_digest (map-get r 'digest)))
               (rejected 'reverification_failed)))))))))
