;;;; Durable hierarchy and dependency admission. Effects require explicit launch.
(defmodule jiti_plan
  (export (create 2) (add 9) (depend 3) (ready 1) (inspect 1)
          (launch 3) (reconcile 1) (verify 3) (block 3) (unblock 2) (cancel 2)))

(defun key (id) (tuple 'hierarchical-plan id))
(defun get-plan (id)
  (let ((p (jiti_kernel:state-get (key id))))
    (case (is_map p) ('true p) (_ (error 'unknown_plan)))))
(defun save (id p)
  (jiti_kernel:state-put (key id) (map-set p 'version (+ 1 (map-get p 'version)))))
(defun text-id (id)
  (case (andalso (is_binary id) (> (byte_size id) 0) (=< (byte_size id) 128))
    ('true 'ok) (_ (error 'invalid_plan_identity))))
(defun node (p id) (maps:get id (map-get p 'nodes)))
(defun children (p id)
  (lists:sort (lists:filter
    (lambda (n) (=:= (map-get (node p n) 'parent) id)) (maps:keys (map-get p 'nodes)))))
(defun lineage (p id)
  (case (map-get (node p id) 'parent)
    ('none ()) (parent (cons parent (lineage p parent)))))
(defun needs (p id)
  (lists:usort (lists:append (lists:map
    (lambda (n) (map-get (node p n) 'deps)) (cons id (lineage p id))))))
(defun visit (p id stack)
  (case (lists:member id stack) ('true (error 'plan_wait_cycle)) (_ 'ok))
  (lists:foreach (lambda (dependency) (node p dependency)
                    (visit p dependency (cons id stack)))
                 (lists:usort (++ (children p id) (needs p id)))))
(defun validate (p)
  (lists:foreach (lambda (id)
                   (case (> (length (lineage p id)) 32)
                     ('true (error 'plan_depth_limit)) (_ 'ok))
                   (visit p id ())) (maps:keys (map-get p 'nodes))) p)
(defun editable (p)
  (case (map-get p 'started) ('false 'ok) (_ (error 'plan_topology_frozen))))
(defun fence (p version)
  (case (=:= version (map-get p 'version)) ('true 'ok) (_ (error 'stale_plan_version))))
(defun replace (p id n) (map-set p 'nodes (map-set (map-get p 'nodes) id n)))

(defun create (id title)
  (text-id id) (text-id title)
  (case (jiti_kernel:state-get (key id))
    ('undefined (jiti_kernel:state-put (key id)
                  (map 'id id 'title title 'version 0 'started 'false 'nodes (map))))
    (_ (error 'plan_already_exists))))
(defun add (plan-id id parent title kind deps priority check spec)
  (let* ((p (get-plan plan-id)) (_ (editable p)) (_ (text-id id)) (_ (text-id title))
         ('false (maps:is_key id (map-get p 'nodes)))
         ('true (< (map_size (map-get p 'nodes)) 128))
         ('true (lists:member kind '(group task)))
         ('true (andalso (is_list deps) (is_integer priority) (is_binary check)
                        (=< (byte_size check) 4096))))
    (case parent
      ('none 'ok)
      (_ (case (=:= (map-get (node p parent) 'kind) 'group)
           ('true 'ok) (_ (error 'task_cannot_have_children)))))
    (case (orelse (andalso (=:= kind 'group) (=:= spec 'none))
                  (andalso (=:= kind 'task) (orelse (=:= spec 'none) (is_map spec))))
      ('true 'ok) (_ (error 'invalid_plan_spec)))
    (let* ((n (map 'id id 'parent parent 'title title 'kind kind 'deps (lists:usort deps)
                   'priority priority 'check check 'spec spec 'phase 'pending 'job 'none))
           (next (validate (replace p id n))))
      (save plan-id next))))
(defun depend (plan-id id dependency)
  (let* ((p (get-plan plan-id)) (_ (editable p)) (n (node p id))
         (next (replace p id (map-set n 'deps (lists:usort (cons dependency (map-get n 'deps)))))))
    (save plan-id (validate next))))

(defun phase (p id)
  (let* ((n (node p id)) (own (map-get n 'phase)) (kids (children p id)))
    (cond
      ((/= own 'pending) own)
      ((=:= (map-get n 'kind) 'task) 'pending)
      ((=:= kids ()) 'pending)
      ('true
       (let ((statuses (lists:map (lambda (k) (phase p k)) kids)))
         (cond
           ((lists:member 'failed statuses) 'failed)
           ((lists:member 'interrupted statuses) 'interrupted)
           ((lists:member 'cancelled statuses) 'cancelled)
           ((lists:member 'blocked statuses) 'blocked)
           ((lists:all (lambda (s) (=:= s 'done)) statuses)
            (if (=:= (map-get n 'check) #B()) 'done 'awaiting_verification))
           ((lists:any (lambda (s) (lists:member s '(running done awaiting_verification))) statuses) 'running)
           ('true 'pending)))))))
(defun admitted (p id)
  (andalso
    (lists:all (lambda (n) (not (lists:member (map-get (node p n) 'phase) '(blocked cancelled done))))
               (cons id (lineage p id)))
    (lists:all (lambda (dependency) (=:= (phase p dependency) 'done)) (needs p id))))
(defun ready (plan-id)
  (let* ((p (get-plan plan-id))
         (ids (lists:filter (lambda (id)
                 (let ((n (node p id)))
                   (andalso (=:= (map-get n 'kind) 'task) (=:= (map-get n 'phase) 'pending)
                            (admitted p id)))) (maps:keys (map-get p 'nodes))))
         (ordered (lists:sort (lambda (a b)
                       (< (tuple (- (map-get (node p a) 'priority)) a)
                          (tuple (- (map-get (node p b) 'priority)) b))) ids)))
    (map 'version (map-get p 'version) 'ready ordered)))
(defun inspect (plan-id)
  (let ((p (get-plan plan-id)))
    (map-set p 'nodes (maps:map (lambda (id n) (map-set n 'status (phase p id))) (map-get p 'nodes)))))

(defun launch (plan-id id version)
  (let* ((p (get-plan plan-id)) (_ (fence p version)) (n (node p id))
         ('true (lists:member id (map-get (ready plan-id) 'ready)))
         (spec (map-get n 'spec)) ('true (is_map spec))
         (configured (if (=:= (map-get spec 'adapter) 'agent)
                         (map-set spec 'logical_id (iolist_to_binary (list plan-id "/" id))) spec))
         (_ (if (=:= (map-get configured 'adapter) 'agent)
                (text-id (map-get configured 'logical_id)) 'ok))
         ((tuple 'ok job) (jiti_processes:start configured)))
    (save plan-id (map-set (replace p id (map-set n 'job job 'phase 'running)) 'started 'true))))

(defun observed-phase (receipt)
  (case (map-get receipt 'status)
    ('succeeded 'awaiting_verification)
    ('running (if (=:= (maps:get 'adapter receipt 'lfe) 'agent) 'awaiting_verification 'running))
    ('failed 'failed) ('stopped 'cancelled) (_ 'interrupted)))
(defun sync-node (n adopt)
  (case (map-get n 'job)
    ('none n)
    (job
     (if (andalso (=:= (map-get n 'phase) 'done) (=:= (map-get job 'adapter) 'lfe)) n
       (let* ((receipt (if adopt (jiti_processes:reconcile job) (jiti_processes:inspect job)))
              (current (observed-phase receipt))
              (same-generation (=:= (maps:get 'generation job 0) (maps:get 'generation receipt 0)))
              (status (if (andalso (=:= (map-get n 'phase) 'done) same-generation
                                   (=:= current 'awaiting_verification)) 'done current)))
         (map-set n 'job receipt 'phase status))))))
(defun reconcile (plan-id)
  (let* ((p (get-plan plan-id))
         (next (map-set p 'nodes (maps:map (lambda (_ n) (sync-node n 'true)) (map-get p 'nodes)))))
    (if (=:= next p) p (save plan-id next))))
(defun verify (plan-id id version)
  (let* ((p (get-plan plan-id)) (_ (fence p version))
         (n (sync-node (node p id) 'false))
         (check (map-get n 'check))
         ('true (andalso (/= check #B()) (admitted p id)))
         ('true (if (=:= (map-get n 'kind) 'group)
                    (andalso (/= (children p id) ())
                      (lists:all (lambda (k) (=:= (phase p k) 'done)) (children p id)))
                    (if (=:= (map-get n 'job) 'none)
                        (=:= (map-get n 'phase) 'pending)
                        (=:= (map-get n 'phase) 'awaiting_verification))))
         ((tuple 'checks 'true 'true) (jiti_kernel:checks (get 'jiti_candidate) ()
             (list (unicode:characters_to_list check)) 250)))
    (save plan-id (map-set (replace p id (map-set n 'phase 'done 'verified_at
                         (erlang:system_time 'millisecond))) 'started 'true))))
(defun block (plan-id id reason)
  (let* ((p (get-plan plan-id)) (n (node p id)))
    (case (lists:member (map-get n 'phase) '(pending blocked))
      ('true (save plan-id (replace p id (map-set n 'phase 'blocked 'reason reason))))
      (_ (error 'cannot_block_started_node)))))
(defun unblock (plan-id id)
  (let* ((p (get-plan plan-id)) (n (node p id)))
    (case (=:= (map-get n 'phase) 'blocked)
      ('true (save plan-id (replace p id (maps:remove 'reason (map-set n 'phase 'pending)))))
      (_ (error 'node_not_blocked)))))
(defun cancel (plan-id id)
  (let* ((p (get-plan plan-id)) (n (node p id)))
    (case (map-get n 'job)
      ('none 'ok)
      (job (case (map-get (jiti_processes:stop-handle job) 'status)
             ('stopped 'ok) (_ (error 'stop_not_observed)))))
    (save plan-id (replace p id (map-set n 'phase 'cancelled)))))
