;;;; Typed convenience operations share the managed candidate and job owner.
;;;; Data is decoded as JSON, never interpolated into executable source.
(defmodule jiti_toolkit (export (apply 2) (inspect 3)))

(defun arg (args key) (map-get args key))
(defun snapshot () (get 'jiti_candidate))
(defun state () (map-get (snapshot) 'state))
(defun required (condition code) (if condition 'ok (error code)))
(defun identity (value)
  (required (andalso (is_binary value) (> (byte_size value) 0) (=< (byte_size value) 128))
            'invalid_identity)
  value)
(defun receipt (details) (map #B("native_tool_result") details))
(defun fenced (args)
  (required (=:= (arg args #B("expected_revision")) (map-get (snapshot) 'revision)) 'stale_revision))

;; Validate the shape and size of JSON at the native boundary too. Objects have
;; binary keys; lists are arrays, not executable forms. Counts include object keys.
(defun json-nodes (value depth)
  (required (=< depth 16) 'json_depth_limit)
  (cond
    ((is_binary value) 1)
    ((is_number value) 1)
    ((lists:member value '(true false null)) 1)
    ((is_list value)
     (+ 1 (lists:sum (lists:map (lambda (v) (json-nodes v (+ depth 1))) value))))
    ((is_map value)
     (+ 1 (lists:sum (lists:map
       (lambda (entry)
         (let (((tuple key v) entry))
           (required (is_binary key) 'non_json_key)
           (+ 1 (json-nodes v (+ depth 1))))) (maps:to_list value)))))
    ('true (error 'non_json_value))))
(defun json-value (source)
  (required (andalso (is_binary source) (=< (byte_size source) 32768)) 'json_size_limit)
  (let ((value (try (json:decode source) (catch ((tuple _ _ _) (error 'invalid_json))))))
    (required (=< (json-nodes value 0) 1024) 'json_node_limit)
    value))
(defun bounded-value (value)
  (required (=< (json-nodes value 0) 1024) 'json_node_limit)
  (required (=< (byte_size (iolist_to_binary (json:encode value))) 32768) 'json_size_limit)
  value)
(defun limited (value count)
  (let ((chars (unicode:characters_to_list value)))
    (map 'text (unicode:characters_to_binary (lists:sublist chars count))
         'truncated (> (length chars) count))))
(defun printed-list
  ((() _) 'true)
  (((cons first rest) depth)
   (andalso (> depth 0) (printed-complete first depth) (printed-list rest (- depth 1)))))
(defun printed-map
  ((() _) 'true)
  (((cons (tuple k v) rest) depth)
   (andalso (> depth 1) (printed-complete k (- depth 1))
            (printed-complete v (- depth 1)) (printed-map rest (- depth 1)))))
(defun printed-complete (value depth)
  (cond
    ((=:= depth 0) 'false)
    ((is_list value) (printed-list value (- depth 1)))
    ((is_tuple value) (printed-list (tuple_to_list value) (- depth 1)))
    ((is_map value) (printed-map (maps:to_list value) depth))
    ('true 'true)))
(defun value-view (value)
  (let* ((printed (limited (unicode:characters_to_binary (lfe_io:print1 value 15)) 4096))
         (encoded (try
           (progn (bounded-value value) (iolist_to_binary (json:encode value)))
           (catch ((tuple _ _ _) 'unavailable)))))
    (map 'value_lfe (map-get printed 'text)
         'value_truncated (orelse (map-get printed 'truncated) (not (printed-complete value 15)))
         'json_available (/= encoded 'unavailable)
         'value_json (if (=:= encoded 'unavailable) 'null encoded))))

;; Read atom keys by comparing existing symbols. Only an explicit put may create
;; a new atom, just as ordinary cooperative LFE source can define a symbol.
(defun key (s args create)
  (let ((name (identity (arg args #B("key")))))
    (case (arg args #B("key_kind"))
      (#B("binary") name)
      (#B("atom")
       (case (lists:filter (lambda (k) (andalso (is_atom k) (=:= (atom_to_binary k 'utf8) name)))
                           (maps:keys s))
         ((list found) found)
         (() (if create (binary_to_atom name 'utf8) (tuple 'missing-key)))))
      (_ (error 'invalid_key_kind)))))
(defun find-value (s args)
  (let ((k (key s args 'false)))
    (if (=:= k (tuple 'missing-key)) 'error (maps:find k s))))
(defun existing (args)
  (case (find-value (state) args)
    ((tuple 'ok value) value) (_ (error 'state_key_not_found))))
(defun edit-state (op args)
  (let ((old (find-value (state) args)))
    (case op
      (#B("delete")
       (if (=:= old 'error) (map 'deleted 'false)
         (progn (jiti_kernel:state-delete (key (state) args 'false)) (map 'deleted 'true))))
      (_
       (let* ((value (case op
                      (#B("put") (json-value (arg args #B("value_json"))))
                      (#B("increment")
                       (let ((v (existing args))
                             (delta (maps:get #B("delta") args 'undefined)))
                         (let ((d (if (=:= delta 'undefined)
                                      (json-value (arg args #B("value_json"))) delta)))
                           (required (andalso (is_integer v) (is_integer d)) 'integer_required)
                           (bounded-value (+ v d)))))
                      (#B("append")
                       (let ((v (existing args)))
                         (required (is_list v) 'list_required)
                         (bounded-value (++ v (list (json-value (arg args #B("value_json"))))))))
                      (#B("merge")
                       (let ((v (existing args)) (addition (json-value (arg args #B("value_json")))))
                         (required (andalso (is_map v) (is_map addition)) 'object_required)
                         (bounded-value (maps:merge v addition))))
                      (_ (error 'unsupported_state_action))))
              (k (key (state) args 'true)))
         (jiti_kernel:state-put k value)
         (maps:merge (map 'changed (/= old (tuple 'ok value))) (value-view value)))))))

(defun function-key (s name arity)
  (identity name)
  (case (lists:filter (lambda (k)
          (let (((tuple symbol count) k))
            (andalso (=:= (atom_to_binary symbol 'utf8) name) (=:= count arity))))
                      (maps:keys (map-get s 'definitions)))
    ((list k) k) (_ (error 'function_not_found))))
(defun function-source (s args)
  (let* ((k (function-key s (arg args #B("name")) (arg args #B("arity"))))
         ((tuple symbol _) k)
         (meta (maps:get k (maps:get 'catalogue s (map))
                 (map 'source (unicode:characters_to_binary (lfe_io:prettyprint1
                   (list 'define-function symbol () (map-get (map-get s 'definitions) k)) -1 0 120)))))
         (chars (unicode:characters_to_list (map-get meta 'source)))
         (start (min (length chars) (arg args #B("offset"))))
         (page (lists:sublist (lists:nthtail start chars) 4000))
         (next (+ start (length page))))
    (map 'name (arg args #B("name")) 'arity (arg args #B("arity"))
         'source (unicode:characters_to_binary page) 'characters (length chars)
         'next_offset (if (< next (length chars)) next 'null))))
(defun function-search (s args)
  (let* ((entries (lists:append (lists:map
                   (lambda (offset) (map-get (jiti_catalogue:page s offset) 'functions))
                   (lists:seq 0 (map_size (map-get s 'definitions)) 50))))
         (query (string:casefold (unicode:characters_to_list (arg args #B("query")))))
         (matches (lists:filter (lambda (f)
           (contains (unicode:characters_to_binary query)
             (iolist_to_binary (list (map-get f 'name) " " (map-get f 'documentation))))) entries)))
    (page matches (arg args #B("offset")) 50 'functions)))
(defun arguments (source)
  (let ((args (json-value source)))
    (required (andalso (is_list args) (=< (length args) 16)) 'argument_array_required)
    args))
(defun test-case (name case-data base)
  (put 'jiti_candidate base)
  (try
    (let* ((expected (json-value (arg case-data #B("expected_json"))))
           (actual (jiti_kernel:invoke name (arguments (arg case-data #B("args_json")))))
           (unchanged (=:= base (snapshot))))
      (maps:merge (map 'passed (andalso unchanged (=:= actual expected))
                       'managed_unchanged unchanged) (value-view actual)))
    (catch ((tuple _ _ _) (map 'passed 'false 'evaluation_error #B("evaluation_failed"))))
    (after (put 'jiti_candidate base))))
(defun expression-check (args base)
  (try
    (let* ((value (jiti_kernel:eval-source (arg args #B("source"))))
           (unchanged (=:= base (snapshot))))
      (maps:merge (map 'passed (andalso (=:= value 'true) unchanged)
                       'managed_unchanged unchanged) (value-view value)))
    (catch ((tuple _ _ _) (map 'passed 'false 'evaluation_error #B("evaluation_failed"))))
    (after (put 'jiti_candidate base))))

(defun record-key (kind args) (tuple kind (identity (arg args #B("id")))))
(defun lookup-record (s kind args)
  (case (maps:find (record-key kind args) (map-get s 'state))
    ((tuple 'ok value) value) (_ (error 'record_not_found))))
(defun external (value)
  (cond
    ((is_map value) (maps:from_list (lists:map (lambda (entry)
      (let (((tuple k v) entry))
        (tuple (if (is_atom k) (atom_to_binary k 'utf8) k) (external v)))) (maps:to_list value))))
    ((is_list value) (lists:map (fun external 1) value))
    ((andalso (is_atom value) (not (lists:member value '(true false null)))) (atom_to_binary value 'utf8))
    ('true value)))
(defun job-view (id recorded)
  (let* ((handle (map-get recorded 'handle))
         (observed (jiti_processes:inspect handle)))
    (map 'id id 'request_hash (map-get recorded 'request_hash)
         'recorded_status (atom_to_binary (map-get handle 'status) 'utf8)
         'observed_status (atom_to_binary (map-get observed 'status) 'utf8)
         'recorded_handle (external handle) 'observed_handle (external observed))))
(defun job-start (args)
  (let* ((k (record-key 'tool-job args))
         (source (arg args #B("source")))
         (timeout (arg args #B("timeout_ms")))
         (_ (required (andalso (is_binary source) (=< (byte_size source) 32768)
                                (is_integer timeout) (> timeout 0) (=< timeout 60000)) 'invalid_job'))
         (hash (binary:encode_hex (crypto:hash 'sha256 (term_to_binary (tuple source timeout))))))
    (case (maps:find k (state))
      ((tuple 'ok existing)
       (required (=:= hash (map-get existing 'request_hash)) 'job_id_conflict)
       (map-set (job-view (arg args #B("id")) existing) 'reused 'true))
      ('error
       (case (jiti_processes:start-once (arg args #B("id")) hash
                 (map 'adapter 'lfe 'source source 'timeout_ms timeout))
         ((tuple 'ok handle)
          (let ((saved (map 'handle handle 'request_hash hash)))
            (jiti_kernel:state-put k saved)
            (map-set (job-view (arg args #B("id")) saved) 'reused 'false)))
         ((tuple 'error 'job_id_conflict) (error 'job_id_conflict))
         (_ (error 'job_start_rejected)))))))
(defun job-update (op args)
  (let* ((saved (lookup-record (snapshot) 'tool-job args))
         (handle (map-get saved 'handle))
         (observed (if (=:= op #B("job_cancel"))
                        (jiti_processes:stop-handle handle) (jiti_processes:reconcile handle))))
    (if (andalso (=:= op #B("job_cancel")) (lists:member (map-get observed 'status) '(unknown stale)))
        (error 'job_handle_unknown)
        (progn
          ;; Unknown observations do not erase a recorded terminal result.
          (if (lists:member (map-get observed 'status) '(unknown stale)) 'ok
              (jiti_kernel:state-put (record-key 'tool-job args) (map-set saved 'handle observed)))
          (job-view (arg args #B("id")) (lookup-record (snapshot) 'tool-job args))))))

(defun contains (query text)
  (let ((q (string:casefold (unicode:characters_to_list query)))
        (t (string:casefold (unicode:characters_to_list text))))
    (/= (string:find t q) 'nomatch)))
(defun page (items offset size field)
  (required (andalso (is_integer offset) (>= offset 0)) 'invalid_offset)
  (let* ((count (length items)) (start (min offset count))
         (chunk (lists:sublist (lists:nthtail start items) size))
         (next (+ start (length chunk))))
    (map field chunk 'count count 'next_offset (if (< next count) next 'null))))
(defun records (s kind)
  (lists:keysort 1 (lists:filtermap (lambda (entry)
    (case entry
      ((tuple (tuple tag id) value) (when (=:= tag kind) (is_binary id))
       (tuple 'true (tuple id value)))
      (_ 'false))) (maps:to_list (map-get s 'state)))))
(defun note-view (id note full)
  (let ((text (map-get note 'text)))
    (map 'id id 'text (if full text (map-get (limited text 256) 'text))
         'text_truncated (andalso (not full) (map-get (limited text 256) 'truncated))
         'tags (map-get note 'tags) 'written_from_revision (map-get note 'written_from_revision))))

(defun inspect (s action args)
  (case action
    (#B("state_get")
     (case (find-value (map-get s 'state) args)
       ('error (map 'found 'false))
       ((tuple 'ok value) (maps:merge (map 'found 'true) (value-view value)))))
    (#B("state_list")
     (let ((entries (lists:sort (lists:filtermap (lambda (entry)
       (let (((tuple k v) entry))
         (if (orelse (is_atom k) (is_binary k))
             (let ((name (if (is_atom k) (atom_to_binary k 'utf8) k)))
               (if (contains (arg args #B("query")) name)
                   (tuple 'true (tuple name (if (is_atom k) #B("atom") #B("binary")) v)) 'false))
             'false))) (maps:to_list (map-get s 'state))))))
       (let ((p (page entries (arg args #B("offset")) 50 'keys)))
         (map-set p 'keys (lists:map (lambda (entry)
           (let (((tuple name kind value) entry))
             (maps:merge (map 'key name 'key_kind kind) (value-view value)))) (map-get p 'keys))))))
    (#B("function_search") (function-search s args))
    (#B("function_source") (function-source s args))
    (#B("job_status") (job-view (arg args #B("id")) (lookup-record s 'tool-job args)))
    (#B("job_list")
     (let ((p (page (records s 'tool-job) (arg args #B("offset")) 50 'jobs)))
       (map-set p 'runtime_job_count (length (jiti_processes:all))
                  'jobs (lists:map (lambda (entry)
         (let (((tuple id saved) entry)) (job-view id saved))) (map-get p 'jobs)))))
    (#B("note_get") (note-view (arg args #B("id")) (lookup-record s 'chat-note args) 'true))
    (op (when (orelse (=:= op #B("note_list")) (=:= op #B("note_search"))))
     (let* ((all (records s 'chat-note))
            (found (if (=:= op #B("note_list")) all
              (lists:filter (lambda (entry)
                (let (((tuple _ note) entry))
                  (contains (arg args #B("query")) (iolist_to_binary
                    (list (map-get note 'text) " " (lists:join " " (map-get note 'tags))))))) all)))
            (p (page found (arg args #B("offset")) 20 'notes)))
       (map-set p 'notes (lists:map (lambda (entry)
         (let (((tuple id note) entry)) (note-view id note 'false))) (map-get p 'notes)))))
    (_ (jiti_workspace_state:inspect s action args))))

(defun dispatch (action args)
  (case action
    (#B("state_put") (edit-state #B("put") args))
    (#B("state_delete") (edit-state #B("delete") args))
    (#B("state_increment") (edit-state #B("increment") args))
    (#B("state_append") (edit-state #B("append") args))
    (#B("state_merge") (edit-state #B("merge") args))
    (#B("state_compare_set")
     (let ((expected (json-value (arg args #B("expected_json")))))
       (if (=:= (find-value (state) args) (tuple 'ok expected))
           (map-set (edit-state #B("put") args) 'matched 'true)
           (map 'matched 'false 'changed 'false))))
    (#B("state_patch")
     (let ((changes (arg args #B("changes"))))
       (required (andalso (is_list changes) (=< (length changes) 32)) 'patch_limit)
       (map 'changes (lists:map (lambda (change) (edit-state (arg change #B("action")) change)) changes))))
    (#B("function_define")
     (jiti_kernel:define (arg args #B("name")) (arg args #B("arguments"))
                         (arg args #B("body")) (arg args #B("documentation")))
     (jiti_catalogue:describe (snapshot) (arg args #B("name")) (length (arg args #B("arguments")))))
    (#B("function_call") (value-view (jiti_kernel:invoke (arg args #B("name")) (arguments (arg args #B("args_json"))))))
    (#B("function_forget")
     (let* ((s (snapshot)) (name (arg args #B("name"))) (arity (arg args #B("arity")))
            ((tuple symbol _) (function-key s name arity))
            (description (jiti_catalogue:describe s name arity))
            (callers (lists:filter (lambda (c)
              (not (andalso (=:= (map-get c 'name) name) (=:= (map-get c 'arity) arity))))
              (map-get description 'callers))))
       (required (orelse (=:= callers ()) (=:= (arg args #B("allow_callers")) 'true)) 'function_has_callers)
       (jiti_kernel:forget symbol arity)
       (map 'forgotten 'true 'retained_callers callers)))
    (#B("function_test")
     (let* ((cases (arg args #B("cases")))
            (_ (required (andalso (is_list cases) (> (length cases) 0) (=< (length cases) 32)) 'case_limit))
            (base (snapshot))
            (results (lists:map (lambda (c) (test-case (arg args #B("name")) c base)) cases)))
       (map 'passed (lists:all (lambda (r) (map-get r 'passed)) results) 'cases results)))
    (#B("expression_check") (expression-check args (snapshot)))
    (#B("job_start") (job-start args))
    (op (when (orelse (=:= op #B("job_reconcile")) (=:= op #B("job_cancel")))) (job-update op args))
    (#B("note_put")
     (let ((text (arg args #B("text"))) (tags (arg args #B("tags"))))
       (required (andalso (is_binary text) (=< (byte_size text) 32768) (is_list tags)
                          (=< (length tags) 16)) 'note_limit)
       (lists:foreach (fun identity 1) tags)
       (let ((note (map 'text text 'tags tags 'written_from_revision (map-get (snapshot) 'revision))))
         (jiti_kernel:state-put (record-key 'chat-note args) note)
         (note-view (arg args #B("id")) note 'true))))
    (#B("note_delete")
     (let* ((k (record-key 'chat-note args)) (found (maps:is_key k (state))))
       (jiti_kernel:state-delete k) (map 'deleted found)))
    (_ (jiti_workspace_state:mutate action args))))

(defun apply (action args)
  (let ((base (snapshot)))
    (try
      (progn
        (if (lists:member action '(#B("function_test") #B("expression_check"))) 'ok (fenced args))
        (receipt (dispatch action args)))
      (catch
        ((tuple _ reason _)
         (put 'jiti_candidate base)
         ;; Do not return conditions containing source, values or credentials.
         (receipt (map 'error (error-code reason))))))))

(defun error-code (reason)
  (if (lists:member reason '(stale_revision invalid_identity json_depth_limit non_json_key
         non_json_value json_size_limit json_node_limit invalid_json invalid_key_kind
         state_key_not_found integer_required list_required object_required
         unsupported_state_action function_not_found invalid_function_request
         invalid_definition reserved_function empty_source invalid_source
         argument_array_required record_not_found invalid_job job_id_conflict
         job_start_rejected job_handle_unknown invalid_offset unknown_inspection
         function_has_callers patch_limit case_limit note_limit unknown_native_tool
         workspace_invalid_project workspace_no_project workspace_project_limit
         workspace_directory_required workspace_project_root_conflict workspace_project_not_found
         workspace_file_changed workspace_pin_limit workspace_scope_changed
         workspace_invalid_manifest workspace_snapshot_exists workspace_snapshot_limit
         workspace_snapshot_not_found workspace_path_not_found workspace_symlink
         hidden_or_traversal_path workspace_source_type_required workspace_inspection_rejected
         workspace_invalid_relative_path workspace_file_byte_limit workspace_source_file_required))
      (atom_to_binary reason 'utf8) #B("native_evaluation_failed")))
