;;;; Native project observations. No external parser, filesystem writer or scheduler.
(defmodule jiti_workspace_project (export (inspect 3) (relative 1) (file 3) (manifest 1)))

(defun arg (args name) (map-get args name))
(defun relative (path)
  (let* ((valid (andalso (is_binary path) (=< (byte_size path) 1024)))
         (chars (if valid (unicode:characters_to_list path) 'invalid)))
    (case (andalso (is_list chars) (not (lists:member 0 chars))
                  (not (lists:member 92 chars))
                  (orelse (=:= chars ()) (/= (hd chars) 47))
                  (lists:all (lambda (part)
                    (andalso (/= part ()) (/= part ".") (/= part "..") (/= (hd part) 46)))
                    (if (=:= chars ()) () (string:split chars "/" 'all))))
      ('true path) (_ (error 'workspace_invalid_relative_path)))))
(defun join (a b)
  (cond ((=:= a #B()) b) ((=:= b #B()) a)
        ('true (iolist_to_binary (list a "/" b)))))
(defun full (p path) (join (relative (map-get p 'root)) (relative path)))
(defun native (op path)
  (case (jiti_workspace:inspect op (map #B("path") path))
    ((tuple 'ok data) data) ((tuple 'error reason) (error reason))))
(defun stat (p path) (native #B("workspace_stat") (full p path)))
(defun file (p path allowance)
  (case (jiti_workspace:source (full p path) allowance)
    ((tuple 'ok data) (map-set data 'path path))
    ((tuple 'error reason _) (error reason))))
(defun used () (case (get 'workspace-observed-bytes) ('undefined 0) (n n)))
(defun observe (p path)
  (case (jiti_workspace:source (full p path) (- 2097152 (used)))
    ((tuple 'ok data)
     (put 'workspace-observed-bytes (+ (used) (map-get data 'bytes)))
     (map-set data 'path path))
    ((tuple 'error reason bytes)
     (put 'workspace-observed-bytes (+ (used) bytes)) (error reason))))
(defun decode (raw)
  (let ((value (unicode:characters_to_binary raw 'utf8 'utf8)))
    (if (is_binary value) (tuple value #B("utf-8"))
      (tuple (unicode:characters_to_binary raw 'latin1 'utf8) #B("latin-1-fallback")))))
(defun chars (binary) (unicode:characters_to_list binary))
(defun text (file) (element 1 (decode (map-get file 'raw))))
(defun lines (file) (string:split (chars (text file)) "\n" 'all))
(defun trim-last-empty (values)
  (if (andalso (/= values ()) (=:= (lists:last values) ()))
      (lists:sublist values (- (length values) 1)) values))
(defun source-lines (file) (trim-last-empty (lines file)))
(defun clip (value count) (unicode:characters_to_binary (lists:sublist value count)))
(defun has (needle haystack insensitive)
  (/= (string:find (if insensitive (string:casefold haystack) haystack)
                  (if insensitive (string:casefold needle) needle)) 'nomatch))
(defun page (rows offset count)
  (let* ((start (min offset (length rows))) (selected (lists:sublist (lists:nthtail start rows) count))
         (next (+ start (length selected))))
    (map 'entries selected 'count (length rows) 'next_offset (if (< next (length rows)) next 'null))))
(defun excluded () '(#B("_build") #B("build") #B("dist") #B("target") #B("node_modules")
                     #B("vendor") #B("venv") #B("__pycache__") #B("artifacts")))
(defun limit (s reason) (map-set s 'limits (lists:usort (cons reason (map-get s 'limits)))))
(defun walk-items
  ((() _ _ _ s) s)
  (((cons item rest) directory depth pending s)
   (let* ((name (map-get item 'name)) (path (join directory name))
          (next (map-set s 'observed (+ 1 (map-get s 'observed)))))
     (cond
       ((> (map-get next 'observed) 2048) (limit next #B("entry_limit")))
       ((map-get item 'symlink)
        (walk-items rest directory depth pending (map-set next 'excluded
          (cons (map 'path path 'reason #B("symlink")) (map-get next 'excluded)))))
       ((map-get item 'directory)
        (if (lists:member name (excluded))
          (walk-items rest directory depth pending (map-set next 'excluded
            (cons (map 'path path 'reason #B("generated_or_vendor")) (map-get next 'excluded))))
          (let* ((listed (map-set next 'entries (cons (map 'path path 'kind #B("directory")) (map-get next 'entries))))
                 (queued (if (orelse (>= depth 6) (>= (length (map-get listed 'queue)) 64))
                   (limit listed #B("depth_or_directory_limit"))
                   (map-set listed 'queue (++ (map-get listed 'queue) (list (tuple path (+ depth 1))))))))
            (walk-items rest directory depth pending queued))))
       ((map-get item 'source)
        (let ((added (map-set next 'files (cons path (map-get next 'files))
                       'entries (cons (map 'path path 'kind #B("source")) (map-get next 'entries)))))
          (if (>= (length (map-get added 'files)) 128)
            (limit added #B("file_limit")) (walk-items rest directory depth pending added))))
       ('true (walk-items rest directory depth pending next))))))
(defun walk-pages (p directory depth offset s)
  (case (jiti_workspace:inspect #B("workspace_list") (map #B("path") (full p directory) #B("offset") offset))
    ((tuple 'error _) (limit s #B("unreadable_directory")))
    ((tuple 'ok listing)
     (let ((next (walk-items (map-get listing 'entries) directory depth () s)))
       (if (orelse (=:= (map-get listing 'next_offset) 'null)
                   (>= (length (map-get next 'files)) 128) (>= (map-get next 'observed) 2048))
         next (walk-pages p directory depth (map-get listing 'next_offset) next))))))
(defun walk-queue (p s)
  (cond
    ((=:= (map-get s 'queue) ()) s)
    ((orelse (>= (map-get s 'visited) 64) (>= (map-get s 'observed) 2048)
             (>= (length (map-get s 'files)) 128)) (limit s #B("directory_or_file_limit")))
    ('true
     (let* (((cons (tuple directory depth) rest) (map-get s 'queue))
            (next (map-set s 'queue rest 'visited (+ 1 (map-get s 'visited)))))
       (walk-queue p (walk-pages p directory depth 0 next))))))
(defun walk (p path)
  (let* ((kind (map-get (stat p path) 'kind))
         (initial (map 'queue (if (=:= kind #B("directory")) (list (tuple path 0)) ())
           'entries (if (=:= kind #B("regular")) (list (map 'path path 'kind #B("source"))) ())
           'files (if (=:= kind #B("regular")) (list path) ())
           'excluded () 'limits () 'observed 0 'visited 0))
         (s (walk-queue p initial)))
    (map 'files (lists:sort (map-get s 'files))
         'entries (lists:sort (lambda (a b) (=< (map-get a 'path) (map-get b 'path))) (map-get s 'entries))
         'complete (=:= (map-get s 'limits) ()) 'limits_hit (map-get s 'limits)
         'excluded (lists:sublist (lists:reverse (map-get s 'excluded)) 100)
         'directories (map-get s 'visited))))
(defun scan (p path)
  (put 'workspace-observed-bytes 0)
  (let* ((tree (walk p path))
         ((tuple files skipped) (lists:foldl (lambda (name accumulator)
           (let (((tuple files skipped) accumulator))
             (try (tuple (cons (observe p name) files) skipped)
               (catch ((tuple _ reason _)
                 (tuple files (cons (map 'path name 'reason (atom_to_binary reason 'utf8)) skipped)))))))
           (tuple () ()) (map-get tree 'files)))
         (coverage (map 'complete (andalso (map-get tree 'complete) (=:= skipped ()))
           'limits_hit (map-get tree 'limits_hit) 'skipped (lists:reverse skipped)
           'excluded (map-get tree 'excluded) 'scanned_files (length files) 'bytes_read (used)
           'scope_path path 'excluded_directories (lists:sort (excluded)))))
    (tuple (lists:reverse files) coverage)))
(defun digest (file) (map 'path (map-get file 'path) 'sha256 (map-get file 'sha256) 'bytes (map-get file 'bytes)))
(defun manifest (p)
  (let (((tuple files coverage) (scan p #B())))
    (json:decode (iolist_to_binary (json:encode (map-set coverage 'files (lists:map (fun digest 1) files)))))))

(defun read-lines (p args)
  (let* ((f (file p (arg args #B("path")) 262144)) (rows (source-lines f))
         (start (min (- (arg args #B("start_line")) 1) (length rows)))
         (end (min (+ start (arg args #B("line_count"))) (length rows)))
         (selected (lists:sublist (lists:nthtail start rows) (- end start)))
         (body (lists:append (lists:join "\n" selected)))
         (content (if (andalso (/= selected ())
           (orelse (< end (length rows)) (=:= (lists:last (chars (text f))) 10)))
           (++ body "\n") body)))
    (map 'path (map-get f 'path) 'sha256 (map-get f 'sha256) 'encoding (element 2 (decode (map-get f 'raw)))
         'start_line (+ start 1) 'end_line end 'total_lines (length rows)
         'content (clip content 12000) 'content_truncated (> (length content) 12000)
         'next_line (if (< end (length rows)) (+ end 1) 'null))))
(defun match-column (line needle insensitive)
  (let* ((haystack (if insensitive (string:casefold line) line))
         (wanted (if insensitive (string:casefold needle) needle))
         (found (string:find haystack wanted)))
    (if (=:= found 'nomatch) -1
      (let ((at (- (length haystack) (length found))))
        (if insensitive (original-column line at 0 0) at)))))
(defun original-column
  ((() _ index _) index)
  (((cons c rest) at index consumed)
   (let ((next (+ consumed (length (string:casefold (list c))))))
     (if (> next at) index (original-column rest at (+ index 1) next)))))
(defun regex-literal (query)
  (iolist_to_binary (lists:map (lambda (c)
    (if (lists:member c "\\.^$|()[]{}*+?") (list 92 c) (list c))) (chars query))))
(defun matches (files query insensitive identifiers)
  (let* ((needle (chars query))
         ((tuple hits capped) (lists:foldl (lambda (f state)
           (let (((tuple hits capped) state))
             (if capped state
               (lists:foldl (lambda (row current)
                 (let* (((tuple line number) row) ((tuple found capped) current)
                        (at (if identifiers
                          (case (re:run (unicode:characters_to_binary line)
                            (iolist_to_binary (list "(?<![\\w$-])" (regex-literal query) "(?![\\w$-])"))
                            '(unicode #(capture first index)))
                            ((tuple 'match (list (tuple byte _)))
                             (length (chars (binary:part (unicode:characters_to_binary line) 0 byte))))
                            (_ -1)) (match-column line needle insensitive))))
                   (cond ((orelse capped (< at 0)) current)
                         ((>= (length found) 50) (tuple found 'true))
                         ('true (tuple (cons (map 'path (map-get f 'path) 'line number 'column (+ at 1)
                           'excerpt (clip (lists:nthtail (max 0 (- at 120)) line) 500)
                           'sha256 (map-get f 'sha256)) found) 'false)))))
                 state (lists:zip (source-lines f) (lists:seq 1 (length (source-lines f))))))))
           (tuple () 'false) files)))
    (tuple (lists:reverse hits) capped)))

(defun symbol-pattern (extension)
  (case extension
    (".lfe" "^\\s*\\((defun|defmacro|defmodule)\\s+([^\\s()]+)")
    (".lisp" "^\\s*\\((defun|defmacro|defclass|defpackage)\\s+([^\\s()]+)")
    (".py" "^\\s*(?:async\\s+)?(def|class)\\s+(\\w+)")
    (".rs" "^\\s*(?:pub(?:\\([^)]*\\))?\\s+)?(?:async\\s+)?(fn|struct|enum|trait|mod)\\s+(\\w+)")
    (".go" "^\\s*(func|type)\\s+(?:\\([^)]*\\)\\s*)?(\\w+)")
    (extension (when (orelse (=:= extension ".js") (=:= extension ".ts")))
     "^\\s*(?:export\\s+)?(?:default\\s+)?(?:async\\s+)?(function|class|interface|type|const)\\s+([\\w$]+)")
    (".md" "^\\s{0,3}(#{1,6})\\s+(.+)")
    (".erl" "^\\s*([a-z][A-Za-z0-9_]*)\\s*\\(")
    (extension (when (orelse (=:= extension ".c") (=:= extension ".h")))
     "^\\s*(?:static\\s+|extern\\s+|inline\\s+)?[\\w][\\w\\s*]+?\\s+([A-Za-z_]\\w*)\\s*\\(")
    (".sh" "^\\s*(?:function\\s+)?([A-Za-z_]\\w*)\\s*\\(\\s*\\)\\s*\\{")
    (".nix" "^\\s*([A-Za-z_][\\w-]*)\\s*=") (_ 'none)))
(defun symbols (f)
  (let* ((pattern (symbol-pattern (filename:extension (chars (map-get f 'path)))))
         (rows (if (=:= pattern 'none) ()
           (lists:filtermap (lambda (row)
             (let (((tuple line number) row))
               (case (re:run (unicode:characters_to_binary line) pattern '(unicode #(capture all_but_first binary)))
                 ((tuple 'match groups)
                  (let* ((name (lists:last groups))
                         (kind (if (=:= (length groups) 1) #B("function") (hd groups))))
                    (tuple 'true (map 'name name 'kind kind 'line number 'end_line 'null
                      'parser #B("lexical") 'path (map-get f 'path) 'sha256 (map-get f 'sha256)))))
                 (_ 'false)))) (lists:zip (source-lines f) (lists:seq 1 (length (source-lines f))))))))
    (tuple (lists:sublist rows 2000) (> (length rows) 2000) (/= pattern 'none))))
(defun code-map (files coverage args)
  (let* (((tuple declarations truncated unsupported) (lists:foldl (lambda (f acc)
           (let* (((tuple rows limited unsupported) acc) ((tuple added cut supported) (symbols f)))
             (tuple (++ rows added) (orelse limited cut)
               (if supported unsupported (cons (map-get f 'path) unsupported))))) (tuple () 'false ()) files))
         (found (lists:filter (lambda (s) (has (chars (arg args #B("query"))) (chars (map-get s 'name)) 'true))
                            (lists:sublist declarations 5000)))
         (result (page found (arg args #B("offset")) 100)))
    (map 'symbols (map-get result 'entries) 'count (map-get result 'count)
         'next_offset (map-get result 'next_offset) 'coverage coverage
         'symbols_truncated (orelse truncated (> (length declarations) 5000))
         'unsupported_formats (lists:reverse unsupported))))
(defun context-file (p pin query)
  (let* ((f (file p (map-get pin 'path) 262144)) (rows (source-lines f))
         (indices (lists:zip rows (lists:seq 0 (- (length rows) 1))))
         (matching (lists:filter (lambda (r) (andalso (/= query #B()) (has (chars query) (element 1 r) 'true))) indices))
         (first (if (=:= matching ()) 0 (element 2 (hd matching))))
         (start (max 0 (- first 3))) (end (min (length rows) (+ first 37)))
         (excerpt (lists:append (lists:join "\n" (lists:sublist (lists:nthtail start rows) (- end start))))))
    (tuple f start end rows excerpt)))
(defun context (p args)
  (let* ((query (arg args #B("query")))
         (pins (lists:sort (lambda (a b)
            (>= (has (chars query) (chars (join (map-get a 'path) (map-get a 'label))) 'true)
                (has (chars query) (chars (join (map-get b 'path) (map-get b 'label))) 'true))) (map-get p 'pins)))
         ((tuple files skipped remaining) (lists:foldl (lambda (pin state)
           (let (((tuple files skipped remaining) state))
             (if (=< remaining 0) state
               (try
                 (let* (((tuple f start end rows excerpt) (context-file p pin query))
                        (content (lists:sublist excerpt (min 3000 remaining))))
                   (tuple (cons (map 'path (map-get pin 'path) 'label (map-get pin 'label)
                     'sha256 (map-get f 'sha256) 'changed_since_pin (/= (map-get pin 'sha256) (map-get f 'sha256))
                     'start_line (+ start 1) 'end_line (+ start (length (string:split content "\n" 'all)))
                     'content (unicode:characters_to_binary content)
                     'excerpt_truncated (orelse (> start 0) (< end (length rows)) (< (length content) (length excerpt)))
                     'evidence_only 'true) files) skipped (- remaining (length content))))
                 (catch ((tuple _ reason _)
                   (tuple files (cons (map 'path (map-get pin 'path) 'reason (atom_to_binary reason 'utf8)) skipped) remaining)))))))
           (tuple () () 12000) (lists:sublist pins 8))))
    (map 'project p 'files (lists:reverse files) 'skipped (lists:reverse skipped)
         'truncated (orelse (< (+ (length files) (length skipped)) (length pins)) (=< remaining 0)) 'evidence_only 'true)))
(defun diff (p baseline)
  (let* (((tuple files coverage) (scan p #B()))
         (old (maps:from_list (lists:map (lambda (f) (tuple (map-get f #B("path")) f))
           (map-get (map-get baseline 'manifest) #B("files")))))
         (new (maps:from_list (lists:map (lambda (f) (tuple (map-get f 'path) f)) files)))
         (changes (lists:foldl (lambda (entry changes)
           (let* (((tuple path previous) entry)
                  (observed (case (maps:find path new)
                    ((tuple 'ok f) (tuple 'ok f))
                    (_ (try (tuple 'ok (observe p path)) (catch ((tuple _ reason _) (tuple 'error reason))))))))
             (case observed
               ((tuple 'error reason)
                (let ((bucket (if (=:= reason 'workspace_path_not_found) 'removed 'unknown)))
                  (map-set changes bucket (cons (map 'path path 'reason (atom_to_binary reason 'utf8)) (map-get changes bucket)))))
               ((tuple 'ok f)
                (if (=:= (map-get f 'sha256) (map-get previous #B("sha256"))) changes
                  (map-set changes 'changed (cons (map 'path path 'before_sha256 (map-get previous #B("sha256"))
                    'after_sha256 (map-get f 'sha256)) (map-get changes 'changed))))))))
           (map 'added (lists:map (lambda (f) (map 'path (map-get f 'path) 'sha256 (map-get f 'sha256)))
             (lists:filter (lambda (f) (not (maps:is_key (map-get f 'path) old))) files))
             'changed () 'removed () 'unknown ()) (lists:sort (maps:to_list old))))
         (complete (andalso (map-get (map-get baseline 'manifest) #B("complete"))
                           (map-get coverage 'complete) (=:= (map-get changes 'unknown) ()))))
    (map 'snapshot_id (map-get baseline 'id) 'changes changes
         'coverage (map-set coverage 'bytes_read (used)) 'baseline_complete (map-get (map-get baseline 'manifest) #B("complete"))
         'comparison_complete complete 'unchanged (andalso complete (lists:all (lambda (v) (=:= v ())) (maps:values changes))))))
(defun inspect (p action args)
  (case action
    (#B("workspace_stat") (maps:merge (map 'path (arg args #B("path"))) (stat p (arg args #B("path")))))
    (#B("workspace_tree")
     (let* ((tree (walk p (arg args #B("path")))) (result (page (map-get tree 'entries) (arg args #B("offset")) 100)))
       (maps:merge (maps:without '(files entries) tree) result)))
    (#B("workspace_read_lines") (read-lines p args))
    (#B("workspace_context") (context p args))
    (#B("workspace_diff") (diff p (arg args #B("baseline"))))
    (op (when (orelse (=:= op #B("workspace_grep")) (=:= op #B("workspace_references")) (=:= op #B("workspace_symbols"))))
     (let (((tuple files coverage) (scan p (arg args #B("path")))))
       (if (=:= op #B("workspace_symbols")) (code-map files coverage args)
         (let* ((references (=:= op #B("workspace_references")))
                ((tuple hits capped) (matches files (arg args (if references #B("symbol") #B("query")))
                  (if references 'false (not (arg args #B("case_sensitive")))) references)))
           (map 'hits hits 'matches_truncated capped 'coverage coverage
                'match_kind (if references #B("lexical_identifier") #B("literal")))))))
    (_ (error 'unknown_inspection))))
