;;;; Project bindings, pins and source manifests belong to managed snapshots.
;;;; Source scans are explicit observations; recovery never reads/runs projects.
(defmodule jiti_workspace_state (export (mutate 2) (inspect 3) (project 1)))

(defun required (value reason) (if value 'ok (error reason)))
(defun field (args key) (map-get args key))
(defun bounded (value maximum)
  (required (andalso (is_binary value) (=< (byte_size value) maximum)) 'workspace_invalid_project)
  value)
(defun identity (value)
  (bounded value 128) (required (> (byte_size value) 0) 'workspace_invalid_project) value)
(defun state (s) (map-get s 'state))
(defun projects (s)
  (lists:keysort 1 (lists:filtermap (lambda (entry)
    (case entry
      ((tuple (tuple 'workspace-project id) p) (when (is_binary id) (is_map p))
       (tuple 'true (tuple id p))) (_ 'false))) (maps:to_list (state s)))))
(defun current (s)
  (case (maps:find (tuple 'workspace-active) (state s))
    ((tuple 'ok id) (map-get (state s) (tuple 'workspace-project id)))
    (_ (error 'workspace_no_project))))
(defun project (s) (project-view s (current s)))
(defun snapshots (s id)
  (lists:keysort 1 (lists:filtermap (lambda (entry)
    (case entry
      ((tuple (tuple 'workspace-snapshot project sid) record) (when (=:= project id))
       (tuple 'true (tuple sid record))) (_ 'false))) (maps:to_list (state s)))))
(defun project-view (s p)
  (map-set p 'snapshots (lists:map (lambda (entry)
    (let (((tuple sid record) entry))
      (map 'id sid 'manifest_hash (map-get record 'manifest_hash)
           'file_count (length (map-get (map-get record 'manifest) #B("files")))
           'complete (map-get (map-get record 'manifest) #B("complete")))))
    (snapshots s (map-get p 'id)))))
(defun stat (path)
  (case (jiti_workspace:inspect #B("workspace_stat") (map #B("path") path))
    ((tuple 'ok info) info) ((tuple 'error reason) (error reason))))
(defun save (p)
  (jiti_kernel:state-put (tuple 'workspace-project (map-get p 'id)) p)
  (project-view (get 'jiti_candidate) p))

(defun inspect (s action args)
  (case action
    (#B("workspace_current")
     (case (maps:find (tuple 'workspace-active) (state s))
       ('error (map 'selected 'false 'project 'null))
       (_ (map 'selected 'true 'project (project-view s (current s))))))
    (#B("workspace_projects")
     (let* ((all (projects s)) (offset (field args #B("offset")))
            (_ (required (andalso (is_integer offset) (>= offset 0)) 'invalid_offset))
            (start (min offset (length all))) (page (lists:sublist (lists:nthtail start all) 20))
            (next (+ start (length page))))
       (map 'projects (lists:map (lambda (entry)
          (let (((tuple _ p) entry))
            (map 'id (map-get p 'id) 'root (map-get p 'root) 'title (map-get p 'title)
                 'pin_count (length (map-get p 'pins))))) page)
            'count (length all) 'next_offset (if (< next (length all)) next 'null))))
    (#B("workspace_snapshot_get")
     (let* ((p (current s))
            (k (tuple 'workspace-snapshot (map-get p 'id) (identity (field args #B("id"))))))
       (case (maps:find k (state s))
         ((tuple 'ok record) record) (_ (error 'workspace_snapshot_not_found)))))
    (#B("workspace_diff")
     (jiti_workspace_project:inspect (project s) action
       (map-set args #B("baseline") (inspect s #B("workspace_snapshot_get") args))))
    (_ (jiti_workspace_project:inspect (project s) action args))))

(defun mutate (action args)
  (let ((s (get 'jiti_candidate)))
    (case action
      (#B("workspace_open")
       (let* ((id (identity (field args #B("id"))))
              (root (jiti_workspace_project:relative (bounded (field args #B("root")) 1024)))
              (info (stat root))
              (_ (required (=:= (map-get info 'kind) #B("directory")) 'workspace_directory_required))
              (old (maps:get (tuple 'workspace-project id) (state s) 'none)))
         (required (orelse (/= old 'none) (< (length (projects s)) 32)) 'workspace_project_limit)
         (required (orelse (=:= old 'none) (=:= (map-get old 'root) root)) 'workspace_project_root_conflict)
         (let ((p (map 'id id 'root root 'title (bounded (field args #B("title")) 512)
                       'description (bounded (field args #B("description")) 4096)
                       'pins (if (=:= old 'none) () (map-get old 'pins)))))
           (jiti_kernel:state-put (tuple 'workspace-active) id)
           (save p))))
      (#B("workspace_use")
       (let* ((id (identity (field args #B("id"))))
              (p (maps:get (tuple 'workspace-project id) (state s) 'none)))
         (required (/= p 'none) 'workspace_project_not_found)
         (jiti_kernel:state-put (tuple 'workspace-active) id)
         (project-view s p)))
      (#B("workspace_pin")
       (let* ((p (current s)) (path (jiti_workspace_project:relative (bounded (field args #B("path")) 1024)))
              (others (lists:filter (lambda (pin) (/= (map-get pin 'path) path)) (map-get p 'pins))))
         (case (field args #B("action"))
           (#B("remove") (save (map-set p 'pins others)))
           (#B("add")
            (let* ((info (jiti_workspace_project:file p path 262144)) (hash (map-get info 'sha256)))
              (required (< (length others) 32) 'workspace_pin_limit)
              (save (map-set p 'pins (++ others (list (map 'path path
                'label (bounded (field args #B("label")) 512) 'sha256 hash
                'bytes (map-get info 'bytes) 'pinned_from_revision (map-get s 'revision))))))))
           (_ (error 'workspace_invalid_project)))))
      (#B("workspace_snapshot")
       (let* ((p (current s)) (id (identity (field args #B("id"))))
              (manifest (jiti_workspace_project:manifest p)) (files (map-get manifest #B("files")))
              (k (tuple 'workspace-snapshot (map-get p 'id) id))
              (all (snapshots s (map-get p 'id))))
         (required (andalso (is_list files) (=< (length files) 128)
                            (=< (byte_size (term_to_binary manifest)) 65536)) 'workspace_invalid_manifest)
         (lists:foreach (lambda (f)
           (bounded (map-get f #B("path")) 1024)
           (required (andalso (is_binary (map-get f #B("sha256")))
                              (=:= (byte_size (map-get f #B("sha256"))) 64)
                              (is_integer (map-get f #B("bytes")))
                              (>= (map-get f #B("bytes")) 0)) 'workspace_invalid_manifest)) files)
         (let* ((hash (binary:encode_hex (crypto:hash 'sha256 (term_to_binary manifest))))
                (old (maps:get k (state s) 'none)))
           (if (/= old 'none)
               (progn (required (=:= (map-get old 'manifest_hash) hash) 'workspace_snapshot_exists)
                      (map-set old 'reused 'true))
               (progn
                 (required (< (length all) 16) 'workspace_snapshot_limit)
                 (let ((record (map 'id id 'project_id (map-get p 'id) 'root (map-get p 'root)
                                   'manifest manifest 'manifest_hash hash
                                   'captured_from_revision (map-get s 'revision))))
                   (jiti_kernel:state-put k record) (map-set record 'reused 'false)))))))
      (_ (error 'unknown_native_tool)))))
