;;;; Durable call descriptors resolve against the current provisional image.
;;;; Multimethods use a specificity partial order, never registration order.
(defmodule jiti_dispatch
  (export (invoke 2) (partial 2) (compose 1) (map-call 2) (fold-call 3)
          (method-put 3) (method-delete 2) (methods 1) (dispatch 2)))

(defun require (test reason) (if test 'ok (error reason)))
(defun name (value)
  (let ((text (if (is_atom value) (atom_to_binary value 'utf8) value)))
    (require (andalso (is_binary text) (> (byte_size text) 0) (=< (byte_size text) 128))
             'invalid_callable_name)
    text))
(defun arguments (args)
  (require (andalso (is_list args) (=< (length args) 1024)) 'invalid_call_arguments)
  args)
(defun invoke (target args)
  (arguments args)
  (case target
    ((tuple 'partial inner bound) (invoke inner (++ bound args)))
    ((tuple 'compose targets)
     (require (=:= (length args) 1) 'composition_requires_one_argument)
     (lists:foldl (lambda (next value) (invoke next (list value))) (car args) targets))
    ((tuple 'dispatch method) (dispatch method args))
    ((tuple 'remote module function)
     (require (andalso (is_atom module) (is_atom function)) 'invalid_remote_callable)
     (erlang:apply module function args))
    (fn (when (is_function fn)) (erlang:apply fn args))
    (_ (jiti_kernel:invoke (name target) args))))
(defun partial (target bound)
  (arguments bound)
  (tuple 'partial target bound))
(defun compose (targets)
  (require (andalso (is_list targets) (=< (length targets) 128)) 'invalid_composition)
  (tuple 'compose targets))
(defun map-call (target values)
  (arguments values)
  (lists:map (lambda (value) (invoke target (list value))) values))
(defun fold-call (target initial values)
  (arguments values)
  (lists:foldl (lambda (value acc) (invoke target (list acc value))) initial values))
(defun selector (value)
  (case value
    ((tuple 'tag _) 'true)
    ((tuple 'map-tag _) 'true)
    (_ (lists:member value '(any integer float number binary atom list tuple map)))))
(defun signature (values)
  (require (andalso (is_list values) (=< (length values) 16)
                   (lists:all (fun selector 1) values) (jiti_kernel:durable values))
           'invalid_dispatch_signature)
  values)
(defun registry-key (method) (tuple 'jiti-dispatch (name method)))
(defun methods (method)
  (case (jiti_kernel:state-get (registry-key method))
    ('undefined ())
    (found (require (is_list found) 'invalid_method_registry) found)))
(defun method-put (method selectors target)
  (signature selectors)
  (require (jiti_kernel:durable target) 'non_durable_callable)
  (let ((old (methods method)))
    (require (orelse (< (length old) 128) (lists:keymember selectors 1 old)) 'method_limit)
    (jiti_kernel:state-put (registry-key method)
      (lists:sort (lists:keystore selectors 1 old (tuple selectors target)))))
  target)
(defun method-delete (method selectors)
  (signature selectors)
  (jiti_kernel:state-put (registry-key method) (lists:keydelete selectors 1 (methods method)))
  'ok)
(defun matches (kind value)
  (case kind
    ('any 'true)
    ('integer (is_integer value))
    ('float (is_float value))
    ('number (is_number value))
    ('binary (is_binary value))
    ('atom (is_atom value))
    ('list (is_list value))
    ('tuple (is_tuple value))
    ('map (is_map value))
    ((tuple 'tag tag)
     (andalso (is_tuple value) (> (tuple_size value) 0) (=:= tag (element 1 value))))
    ((tuple 'map-tag tag)
     (andalso (is_map value) (maps:is_key #B("type") value)
              (=:= tag (map-get value #B("type")))))))
(defun accepts (selectors args)
  (andalso (=:= (length selectors) (length args))
    (lists:all (lambda (pair) (matches (element 1 pair) (element 2 pair))) (lists:zip selectors args))))
(defun subset (a b)
  (orelse (=:= a b) (=:= b 'any)
    (andalso (=:= b 'number) (lists:member a '(integer float)))
    (andalso (=:= b 'tuple) (is_tuple a) (=:= (element 1 a) 'tag))
    (andalso (=:= b 'map) (is_tuple a) (=:= (element 1 a) 'map-tag))))
(defun dominates (a b)
  (andalso (/= a b)
    (lists:all (lambda (pair) (subset (element 1 pair) (element 2 pair))) (lists:zip a b))))
(defun dispatch (method args)
  (arguments args)
  (let* ((candidates (lists:filter (lambda (entry) (accepts (element 1 entry) args)) (methods method)))
         (best (lists:filter (lambda (entry)
           (not (lists:any (lambda (other) (dominates (element 1 other) (element 1 entry))) candidates))) candidates)))
    (case best
      ((list (tuple _ target)) (invoke target args))
      (() (error 'no_applicable_method))
      (_ (error 'ambiguous_dispatch)))))
