;;;; Explicitly owned asynchronous LFE jobs and remote agents.erl farm actors.
;;;; Public receipts contain no PIDs, monitors, timers, snapshots or source.
(defmodule jiti_processes
  (behaviour gen_server)
  (export (start_link 0) (configure 1) (start 1) (start-once 3) (status 1) (stop 1) (all 0)
          (inspect 1) (reconcile 1) (stop-handle 1)
          (init 1) (handle_call 3) (handle_cast 2) (handle_info 2)
          (terminate 2) (code_change 3)))

(defun start_link () (gen_server:start_link (tuple 'local 'jiti_processes) 'jiti_processes () ()))
(defun configure (owner) (gen_server:call 'jiti_processes (tuple 'configure owner)))
(defun valid-handle (handle)
  (case (andalso (is_map handle) (is_binary (maps:get 'id handle 'none))
                 (lists:member (maps:get 'adapter handle 'none) '(lfe agent)))
    ('true 'ok) (_ (error 'invalid_process_handle))))
(defun inspect (handle) (valid-handle handle) (gen_server:call 'jiti_processes (tuple 'inspect handle 'false) 7000))
(defun reconcile (handle) (valid-handle handle) (gen_server:call 'jiti_processes (tuple 'inspect handle 'true) 7000))
(defun stop-handle (handle) (valid-handle handle) (gen_server:call 'jiti_processes (tuple 'stop-handle handle) 7000))
(defun start (spec)
  (gen_server:call 'jiti_processes (tuple 'start spec (get 'jiti_candidate)) 7000))
(defun start-once (key hash spec)
  (gen_server:call 'jiti_processes (tuple 'start-once key hash spec (get 'jiti_candidate)) 7000))
(defun status (id) (gen_server:call 'jiti_processes (tuple 'status id) 7000))
(defun stop (id) (gen_server:call 'jiti_processes (tuple 'stop id) 7000))
(defun all () (gen_server:call 'jiti_processes 'list 7000))

(defun init (_)
  (process_flag 'trap_exit 'true)
  (tuple 'ok (map 'jobs (map) 'generation
    (iolist_to_binary (list (os:getpid) "-" (integer_to_list (erlang:system_time 'microsecond))))
    'sequence 0 'owner (persistent_term:get 'jiti_process_owner 'none))))
(defun public (job) (maps:without '(pid monitor timer) job))
(defun terminal (job status)
  (map-set job 'status status 'finished_at (erlang:system_time 'millisecond)))
(defun result-summary (job result)
  (let* ((printed (unicode:characters_to_binary (lfe_io:prettyprint1 result 15 0 120)))
         (large (> (byte_size printed) 32768)))
    (map-set job 'result (if large #B("background_result_exceeds_summary_limit") printed)
                 'result_truncated large)))

(defun remote-connect (node)
  (case (andalso (is_atom node) (lists:suffix "@127.0.0.1" (atom_to_list node)))
    ('true 'ok) (_ (error 'local_node_required)))
  (case (erlang:node)
    ('nonode@nohost
     (application:set_env 'kernel 'inet_dist_use_interface (tuple 127 0 0 1))
     (case (net_kernel:start (list (list_to_atom (++ "jiti_jobs_" (os:getpid) "@127.0.0.1")) 'longnames))
       ((tuple 'ok _) 'ok) (_ (error 'distribution_unavailable))))
    (_ 'ok))
  (case (net_kernel:connect_node node) ('true 'ok) (_ (error 'remote_unavailable))))

(defun create (id spec snapshot owner)
  (let* ((adapter (map-get spec 'adapter))
         (base (map 'id id 'adapter adapter 'status 'running
                    'started_at (erlang:system_time 'millisecond))))
    (case adapter
      ('lfe
       (let* ((source (map-get spec 'source))
              (timeout (maps:get 'timeout_ms spec 1000))
              ('true (andalso (is_binary source) (=< (byte_size source) 32768)
                             (is_integer timeout) (> timeout 0) (=< timeout 60000)))
              (owner (self))
              ((tuple pid monitor) (spawn_opt
                (lambda () (! owner (tuple 'job_result id
                  (jiti_kernel:background snapshot (unicode:characters_to_list source))))) '(link monitor)))
              (timer (erlang:send_after timeout (self) (tuple 'job_timeout id))))
         (map-set base 'pid pid 'monitor monitor 'timer timer)))
      ('agent
       (let* ((node (map-get spec 'node))
              ('ok (remote-connect node))
              (logical-id (map-get spec 'logical_id))
              (remote (rpc:call node 'persistent_agent_service 'create
                        (list owner logical-id (maps:get 'name spec #B("Jiti durable actor"))
                              (maps:get 'tools spec ())) 4000)))
         (case remote
           (record (when (is_map record))
            (map-set base 'node node 'owner owner 'logical_id logical-id
                          'generation (map-get record 'generation)
                          'agent_id (map-get record 'agent_id)
                          'tools (maps:get 'tools record ())
                          'status (if (=:= (map-get record 'phase) 'running) 'running 'stopped)))
           (_ (error 'durable_actor_create_failed)))))
      (_ (error 'unsupported_process_adapter)))))

(defun remote-view (job adopt owner)
  (try
    (let* (('true (=:= (map-get job 'owner) owner))
           (node (map-get job 'node)) ('ok (remote-connect node))
           (record (rpc:call node 'persistent_agent_service 'inspect
                     (list owner (map-get job 'logical_id)) 4000))
           ('true (is_map record))
           (generation (map-get record 'generation))
           (same (=:= generation (map-get job 'generation))))
      (if (orelse same adopt)
          (map-set job 'generation generation 'status
            (if (=:= (map-get record 'phase) 'running) 'running 'stopped)
            'observation (maps:with '(agent_id generation phase) record))
          (map-set job 'status 'stale)))
    (catch ((tuple _ _ _) (map-set job 'status 'unknown)))))

(defun remote-stop (job owner)
  (try
    (let* (('true (=:= (map-get job 'owner) owner))
           (node (map-get job 'node)) ('ok (remote-connect node))
           (record (rpc:call node 'persistent_agent_service 'stop
                     (list owner (map-get job 'logical_id) (map-get job 'generation)) 4000)))
      (case record
        (r (when (is_map r)) (map-set job 'status (if (=:= (map-get r 'phase) 'stopped) 'stopped 'unknown)))
        ((tuple 'error 'stale_generation) (map-set job 'status 'stale))
        (_ (map-set job 'status 'unknown))))
    (catch ((tuple _ _ _) (map-set job 'status 'unknown)))))

(defun stop-owned (job)
  (case (map-get job 'status)
    ('running
     (case (map-get job 'adapter)
       ('lfe (exit (map-get job 'pid) 'kill)
             (erlang:cancel_timer (map-get job 'timer)) (terminal job 'stopped))
       ('agent (error 'durable_actor_requires_fenced_stop))))
    (_ job)))

(defun admit (spec snapshot state)
  (try
    (let* ((jobs (map-get state 'jobs))
           (active (length (lists:filter
                     (lambda (j) (=:= (map-get j 'status) 'running)) (maps:values jobs))))
           ('true (andalso (< active 16) (< (map_size jobs) 256)))
           (sequence (+ 1 (map-get state 'sequence)))
           (id (iolist_to_binary (list (map-get state 'generation) "-" (integer_to_list sequence))))
           (job (create id spec snapshot (map-get state 'owner)))
           (recorded (if (maps:is_key 'request_key spec)
                         (map-set job 'request_key (map-get spec 'request_key)
                                      'request_hash (map-get spec 'request_hash)) job)))
      (tuple 'reply (tuple 'ok (public recorded))
             (map-set state 'jobs (map-set jobs id recorded) 'sequence sequence)))
    (catch ((tuple _ _ _) (tuple 'reply (tuple 'error 'process_start_rejected) state)))))

(defun handle_call
  (((tuple 'configure owner) _ state)
   (case (map-get state 'owner)
     ('none (persistent_term:put 'jiti_process_owner owner)
            (tuple 'reply 'ok (map-set state 'owner owner)))
     (current (tuple 'reply (if (=:= current owner) 'ok (tuple 'error 'owner_is_immutable)) state))))
  (((tuple 'inspect job adopt) _ state)
   (if (=:= (map-get job 'adapter) 'agent)
       (tuple 'reply (remote-view job adopt (map-get state 'owner)) state)
       (let ((current (maps:get (map-get job 'id) (map-get state 'jobs) (map-set job 'status 'unknown))))
         (tuple 'reply (public current) state))))
  (((tuple 'stop-handle job) _ state)
   (if (=:= (map-get job 'adapter) 'agent)
       (tuple 'reply (remote-stop job (map-get state 'owner)) state)
       (case (maps:find (map-get job 'id) (map-get state 'jobs))
         ((tuple 'ok current)
          (let ((updated (stop-owned current)))
            (tuple 'reply (public updated) (map-set state 'jobs (map-set (map-get state 'jobs) (map-get job 'id) updated)))))
         (_ (tuple 'reply (map-set job 'status 'unknown) state)))))
  (((tuple 'start spec snapshot) _ state) (admit spec snapshot state))
  (((tuple 'start-once key hash spec snapshot) _ state)
   (let ((matches (lists:filter (lambda (job) (=:= (maps:get 'request_key job 'none) key))
                                (maps:values (map-get state 'jobs)))))
     (case matches
       (() (if (andalso (is_binary key) (> (byte_size key) 0) (=< (byte_size key) 128)
                        (is_binary hash) (=:= (byte_size hash) 64) (=:= (map-get spec 'adapter) 'lfe))
               (admit (map-set spec 'request_key key 'request_hash hash) snapshot state)
               (tuple 'reply (tuple 'error 'invalid_process_request_key) state)))
       ((list job)
        (tuple 'reply (if (=:= (map-get job 'request_hash) hash)
                          (tuple 'ok (public job)) (tuple 'error 'job_id_conflict)) state)))))
  (((tuple 'status id) _ state)
   (case (maps:find id (map-get state 'jobs))
     ((tuple 'ok job)
      (let ((updated (if (=:= (map-get job 'adapter) 'agent)
                         (remote-view job 'false (map-get state 'owner)) job)))
        (tuple 'reply (public updated) (map-set state 'jobs (map-set (map-get state 'jobs) id updated)))))
     ('error (tuple 'reply (map 'id id 'status 'unknown) state))))
  (((tuple 'stop id) _ state)
   (case (maps:find id (map-get state 'jobs))
     ((tuple 'ok job)
      (if (=:= (map-get job 'adapter) 'agent)
          (tuple 'reply (tuple 'error 'fenced_handle_required) state)
          (let ((updated (stop-owned job)))
            (tuple 'reply (public updated) (map-set state 'jobs (map-set (map-get state 'jobs) id updated))))))
     ('error (tuple 'reply (map 'id id 'status 'unknown) state))))
  (('list _ state) (tuple 'reply (lists:map (fun public 1) (maps:values (map-get state 'jobs))) state))
  ((_ _ state) (tuple 'reply (tuple 'error 'unsupported_process_action) state)))

(defun handle_cast (_ state) (tuple 'noreply state))
(defun handle_info
  (((tuple 'job_result id result) state)
   (case (maps:find id (map-get state 'jobs))
     ((tuple 'ok job)
      (if (=:= (map-get job 'status) 'running)
          (let* ((status (if (=:= (element 1 result) 'ok) 'succeeded 'failed))
                 (_ (erlang:cancel_timer (map-get job 'timer)))
                 (updated (result-summary (terminal job status) result)))
            (tuple 'noreply (map-set state 'jobs (map-set (map-get state 'jobs) id updated))))
          (tuple 'noreply state)))
     (_ (tuple 'noreply state))))
  (((tuple 'job_timeout id) state)
   (case (maps:find id (map-get state 'jobs))
     ((tuple 'ok job)
      (if (=:= (map-get job 'status) 'running)
          (progn (exit (map-get job 'pid) 'kill)
            (tuple 'noreply (map-set state 'jobs
              (map-set (map-get state 'jobs) id (terminal job 'failed)))))
          (tuple 'noreply state)))
     (_ (tuple 'noreply state))))
  (((tuple 'DOWN monitor 'process _ _) state)
   (let ((jobs (maps:map (lambda (_ job)
                          (if (andalso (=:= (maps:get 'monitor job 'none) monitor)
                                       (=:= (map-get job 'status) 'running))
                              (terminal job 'failed) job)) (map-get state 'jobs))))
     (tuple 'noreply (map-set state 'jobs jobs))))
  ((_ state) (tuple 'noreply state)))

(defun terminate (_ state)
  (lists:foreach (lambda (j)
                   (case (andalso (=:= (map-get j 'adapter) 'lfe)
                                  (=:= (map-get j 'status) 'running))
                     ('true (exit (map-get j 'pid) 'kill)) (_ 'ok)))
                 (maps:values (map-get state 'jobs))) 'ok)
(defun code_change (_ state _) (tuple 'ok state))
