(eval-when (:compile-toplevel :load-toplevel :execute) (require :sb-concurrency) (require :sb-posix))
(defpackage :image-agent
  (:use :cl)
  (:export :make-world :world-package :world-observe :world-snapshot :world-restore
           :world-export :world-import :world-validate-form :world-record-form :world-managed-state :world-catalogue
           :make-session :session-step :run :close-session :session-events
           :session-status :session-world :session-budget :session-store
           :recover-session :publish-revision :load-revision :list-revisions :rollback-revision :*store-boundary-hook*
           :make-reference-world :reference-table :parse-one-form :validate-form
           :make-property-check :make-openai-proposer :parse-action :parse-sse :configuration-error))
(in-package :image-agent)
(defstruct (world (:constructor make-world
                      (&key package observe snapshot restore export import managed-state catalogue
                            (record-form (constantly nil)) (validate-form (constantly nil)))))
  package observe snapshot restore export import managed-state catalogue record-form validate-form active-session
  (ownership-lock (sb-thread:make-mutex :name "world owner")))
(defstruct (session (:constructor %make-session))
  world goal goals invariants budget store recovery-history interactive outcome last-view (status :starting) (events nil)
  (inbox (sb-concurrency:make-mailbox)) (outbox (sb-concurrency:make-mailbox))
  thread (controller-lock (sb-thread:make-mutex :name "session controller"))
  (generation 0) (pause-count 0) operation (operations nil) (closed nil))
(define-condition configuration-error (error)
  ((message :initarg :message :reader configuration-message))
  (:report (lambda (c s) (write-string (configuration-message c) s))))
(define-condition policy-error (error) ())
(define-condition infrastructure-error (error) ())
(defvar *handling-error* nil)
(defvar *operation-sequence* 0)
(defvar *operation-id-lock* (sb-thread:make-mutex :name "operation IDs"))
(defun copy-managed-value (value &optional (active (make-hash-table :test 'eq)))
  "Copy mutable components of the reference adapter's readable trees."
  (if (or (consp value) (vectorp value))
      (progn
        (when (gethash value active) (error "Cyclic managed value"))
        (setf (gethash value active) t)
        (prog1 (cond ((consp value) (cons (copy-managed-value (car value) active)
                                        (copy-managed-value (cdr value) active)))
                     ((stringp value) (copy-seq value))
                     (t (let ((copy (copy-seq value)))
                          (dotimes (i (length copy)) (setf (aref copy i) (copy-managed-value (aref value i) active)))
                          copy)))
          (remhash value active)))
      value))
(defun capture-managed-state (world)
  "Capture a deterministic readable tree. Compare its case-sensitive representation.
EQUALP on strings/characters alone would incorrectly equate uppercase and lowercase."
  (let ((value (funcall (world-managed-state world))) (active (make-hash-table :test 'eq)))
    (labels ((walk (x)
               (cond ((or (consp x) (vectorp x))
                      (when (gethash x active) (error "Cyclic managed state"))
                      (setf (gethash x active) t)
                      (if (consp x) (progn (walk (car x)) (walk (cdr x)))
                          (map nil #'walk x))
                      (remhash x active))
                     ((not (or (null x) (symbolp x) (numberp x) (characterp x)))
                      (error "Managed state must be a readable tree")))))
      (walk value))
    (let ((*print-readably* t) (*print-circle* nil) (*print-level* nil) (*print-length* nil)
          (*package* (find-package :keyword)) (*readtable* (copy-readtable nil))
          (*print-case* :upcase) (*print-pretty* nil) (*print-array* t) (*print-base* 10) (*print-radix* nil))
      (map 'vector #'char-code (prin1-to-string value)))))
(defclass limited-output (sb-gray:fundamental-character-output-stream)
  ((buffer :initform (make-string-output-stream) :reader output-buffer)
   (count :initform 0 :accessor output-count)
   (limit :initarg :limit :reader output-limit)
   (tag :initarg :tag :reader output-tag)))
(defmethod sb-gray:stream-write-char ((stream limited-output) character)
  (when (>= (output-count stream) (output-limit stream)) (throw (output-tag stream) :truncated))
  (incf (output-count stream)) (write-char character (output-buffer stream)) character)
(defmethod sb-gray:stream-line-column ((stream limited-output)) (declare (ignore stream)) nil)
(defun printed-value (value &optional (limit 4096))
  (let* ((tag (gensym)) (stream (make-instance 'limited-output :limit limit :tag tag))
         (status (catch tag
                   (handler-case
                       (let ((*print-level* nil) (*print-length* nil) (*print-circle* t))
                         (prin1 value stream) :complete)
                     (error () :unprintable)))))
    (list :text (get-output-stream-string (output-buffer stream))
          :truncated (not (eq status :complete)) :print-error (eq status :unprintable))))
(defun printed-values (values)
  (loop with remaining = 12000 for value in values for index below 32
        while (plusp remaining)
        for record = (printed-value value (min 4096 remaining))
        do (decf remaining (max 1 (length (getf record :text)))) collect record))
(defun begin-operation (s action)
  ;; Preallocate completion fields so SETF GETF preserves the plist shared by history.
  (let ((record (list :id (format nil "operation-~d-~d-~d" (get-universal-time)
                                  (sb-posix:getpid) (sb-thread:with-mutex (*operation-id-lock*) (incf *operation-sequence*)))
                      :intent (getf action :action) :target (getf action :revision) :preview (not (null (getf action :preview)))
                      :source (when (stringp (getf action :source)) (subseq (getf action :source) 0 (min 16384 (length (getf action :source))))) :status :running :outcome nil :revision nil
                      :base-revision (when (session-store s) (current-revision (session-store s))))))
    (setf (session-operation s) record)
    (push record (session-operations s))
    (emit s :operation-start :record (copy-list record))))
(defun finish-operation (s status)
  (when (session-operation s)
    (setf (getf (session-operation s) :status) status
          (getf (session-operation s) :outcome) (copy-tree (session-outcome s))
          (getf (session-operation s) :revision) (when (session-store s) (current-revision (session-store s))))
    (emit s :operation-finish :record (copy-tree (session-operation s)))
    (setf (session-operation s) nil
          (session-operations s) (subseq (session-operations s) 0 (min 100 (length (session-operations s)))))))
(defun catalogue-info (entry &key (include-source t))
  (flet ((text (key limit)
           (let ((value (getf entry key)))
             (when (stringp value) (subseq value 0 (min limit (length value))))))
         (truncated (key limit)
           (let ((value (getf entry key))) (and (stringp value) (> (length value) limit)))))
    (list :name (text :name 256) :arguments (printed-value (getf entry :arguments) 512)
          :documentation (text :documentation 512) :documentation-truncated (truncated :documentation 512)
          :source (and include-source (text :source 4096)) :source-truncated (and include-source (truncated :source 4096)))))
(defun catalogue-summary (entry)
  (let ((copy (copy-list entry)))
    (remf copy :source)
    (when (stringp (getf copy :documentation))
      (setf (getf copy :documentation) (subseq (getf copy :documentation) 0 (min 256 (length (getf copy :documentation))))))
    (printed-value copy 512)))
(defun inspect-action (s action)
  (case (getf action :action)
    (:inspect
     (let* ((entries (funcall (world-catalogue (session-world s))))
            (offset (or (getf action :offset) 0))
            (start (min (length entries) (max 0 offset)))
            (end (min (length entries) (+ start 50))))
       (setf (session-outcome s)
             (list :catalogue (mapcar #'catalogue-summary (subseq entries start end))
                   :catalogue-infos (mapcar (lambda (entry) (catalogue-info entry :include-source nil)) (subseq entries start end))
                   :catalogue-count (length entries) :catalogue-truncated (< end (length entries))
                   :next-offset (and (< end (length entries)) end)))))
    (:describe
     (let* ((name (getf action :name))
            (entry (and (stringp name) (find name (funcall (world-catalogue (session-world s)))
                         :key (lambda (e) (getf e :name)) :test #'string-equal))))
       (setf (session-outcome s) (list :function-info (and entry (catalogue-info entry)) :function (and entry (printed-value entry)) :found (not (null entry))))))
    (:operations
     (let ((records (remove (session-operation s) (session-operations s) :test #'eq)))
       (setf (session-outcome s) (list :operations (mapcar (lambda (r) (printed-value r 1024))
                                               (subseq records 0 (min 25 (length records))))
                                     :operation-records (copy-tree (subseq records 0 (min 25 (length records))))
                                     :operation-count (length records) :operations-truncated (> (length records) 25)))))))
(defun bounded (value &optional (limit 4096))
  (handler-case
      (let* ((*print-level* 6) (*print-length* 30) (*print-circle* t)
             (text (princ-to-string value)))
        (subseq text 0 (min limit (length text))))
    (error () "<unprintable>")))
(defun emit (session kind &rest details)
  (let ((event (list* :event kind :operation-id (getf (session-operation session) :id) :generation (session-generation session) details)))
    (push event (session-events session))
    (when (and (session-store session) (fboundp 'append-journal))
      (handler-case (append-journal session event)
        (error () (error 'infrastructure-error))))))
(defun parse-one-form (source package)
  (unless (and (stringp source) (<= (length source) 16384))
    (error 'policy-error))
  (let ((*read-eval* nil) (*readtable* (copy-readtable nil)) (*package* package)
        (eof (gensym)))
    (with-input-from-string (s source)
      (let ((form (read s nil eof)))
        (when (or (eq form eof) (not (eq (read s nil eof) eof)))
          (error 'policy-error))
        form))))
(defun validate-form (form)
  ;; Conservative cooperative gate. It intentionally rejects even quoted kernel symbols.
  (let ((seen (make-hash-table :test 'eq)))
    (labels ((walk (x)
               (when (and (symbolp x)
                          (or (and (symbol-package x)
                                   (member (package-name (symbol-package x))
                                           '("IMAGE-AGENT" "IMAGE-AGENT/CLI" "IMAGE-AGENT/EXPERIMENTS" "IMAGE-AGENT/TERMINAL") :test #'equal))
                              (member (symbol-name x)
                                      '("UNLOCK-PACKAGE" "WITHOUT-PACKAGE-LOCKS"
                                        "DISABLE-PACKAGE-LOCKS" "INVOKE-RESTART"
                                        "INVOKE-RESTART-INTERACTIVELY") :test #'equal)))
                 (error 'policy-error))
               (when (or (consp x) (and (vectorp x) (not (stringp x))))
                 (when (gethash x seen) (error 'policy-error))
                 (setf (gethash x seen) t)
                 (if (consp x) (progn (walk (car x)) (walk (cdr x)))
                     (map nil #'walk x)))))
      (walk form)))
  form)
(defun check-predicates (checks)
  (mapcar (lambda (entry)
            (handler-case
                (let ((result (funcall (cdr entry))))
                  (if (and (consp result) (eq (car result) :property-result))
                      (list* :name (car entry) result)
                      (list :name (car entry) :status (if result :pass :fail))))
              (error (c) (list :name (car entry) :status :error
                               :condition (bounded c))))) checks))
(defun all-pass-p (results)
  (every (lambda (r) (eq (getf r :status) :pass)) results))
(defun report-state (s status &rest details)
  (setf (session-status s) status)
  (incf (session-generation s))
  (let* ((*package* (world-package (session-world s)))
         (*print-level* 6) (*print-length* 30) (*print-circle* t)
         (observation (bounded (prin1-to-string (funcall (world-observe (session-world s)))))))
    (emit s :observation :status status :world observation)
    (setf (session-last-view s)
     (list* :status status :generation (session-generation s)
            :goal (session-goal s) :observation observation
            :recovery-history (bounded (session-recovery-history s))
            :operation-id (or (getf (session-operation s) :id) (getf (session-outcome s) :operation-id))
            :remaining (session-budget s) :outcome (session-outcome s)
            :revision (when (session-store s) (current-revision (session-store s)))
            :history (bounded (reverse (subseq (session-events s) 0 (min 8 (length (session-events s))))) 4096)
            details))
    (sb-concurrency:send-message (session-outbox s) (session-last-view s))))
(defun receive-action (s)
  (loop
    for action = (sb-concurrency:receive-message (session-inbox s))
    do (when (eq (getf action :action) :cancel) (throw 'abort-attempt :cancelled))
       (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
       (decf (session-budget s))
       (emit s :action :proposal (bounded action 17000))
       (if (= (or (getf action :generation) -1) (session-generation s))
           (return action)
           (progn
             (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
             (report-state s (session-status s) :rejected :stale-observation
                           :condition (getf (session-last-view s) :condition)
                           :restarts (getf (session-last-view s) :restarts)
                           :goals (getf (session-last-view s) :goals)
                           :invariants (getf (session-last-view s) :invariants))))))
(defun evaluate-source (s source)
  (let* ((w (session-world s))
         (*package* (world-package w))
         (form (validate-form (parse-one-form source *package*)))
         (*standard-output* (make-broadcast-stream))
         (*error-output* (make-broadcast-stream)))
    (handler-case (funcall (world-validate-form w) form)
      (error () (error 'policy-error)))
    (multiple-value-prog1 (eval form)
      (handler-case (funcall (world-record-form w) form)
        (error () (error 'infrastructure-error))))))
(defun condition-loop (s condition baseline)
  (when (typep condition 'infrastructure-error) (throw 'abort-attempt :infrastructure-failed))
  (when (or *handling-error* (typep condition 'policy-error)
            (typep condition 'sb-ext:package-lock-violation))
    (throw 'abort-attempt :rejected))
  (let ((*handling-error* t))
    (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
    (setf (session-outcome s) (list :commit :signaled :condition (bounded condition)))
    (emit s :condition :type (string (type-of condition)) :message (bounded condition))
    (loop
      for pause = (incf (session-pause-count s))
      for restarts = (remove-if (lambda (r) (member r baseline))
                                (compute-restarts condition))
      for menu = (loop for r in restarts for i from 0
                       collect (list :id (format nil "~d/~d" pause i)
                                     :name (and (restart-name r)
                                                (string (restart-name r)))
                                     :report (bounded r)))
      do (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
         (report-state s :paused :condition (bounded condition) :restarts menu
                       :goals (check-predicates (session-goals s))
                       :invariants (check-predicates (session-invariants s)))
         (let ((action (receive-action s)))
           (case (getf action :action)
             ((:develop :execute)
              (when (getf action :preview) (emit s :rejected :reason :nested-preview) (throw 'abort-attempt :nested-preview))
              (handler-bind ((error (lambda (c) (declare (ignore c))
                                       (throw 'abort-attempt :repair-failed))))
                (evaluate-source s (getf action :source))))
             (:resume
              (let ((index (position (getf action :restart-id) menu
                                     :key (lambda (x) (getf x :id)) :test #'equal)))
                (when index
                  (let ((args
                          (handler-bind ((error (lambda (c) (declare (ignore c))
                                                   (throw 'abort-attempt :repair-failed))))
                            (evaluate-source s (or (getf action :arguments) "nil")))))
                    (unless (listp args) (throw 'abort-attempt :invalid-arguments))
                    (emit s :restart :id (getf action :restart-id))
                    ;; Errors before a restart transfers control occur inside our condition
                    ;; handler, where the original handler cluster is inactive. Restore the
                    ;; attempt rather than allowing argument/body errors to fault the worker.
                    (handler-bind ((error (lambda (c) (declare (ignore c))
                                           (throw 'abort-attempt :restart-failed))))
                      (apply #'invoke-restart (nth index restarts) args))))))
             (:rollback (throw 'abort-attempt (list :rollback (getf action :revision))))
             ((:inspect :describe :operations) (inspect-action s action))
             (:check nil)
             (:abort (throw 'abort-attempt :aborted))
             (otherwise (emit s :rejected :reason :invalid-action)))))))
(defun attempt (s action)
  (begin-operation s action)
  (let* ((w (session-world s)) (checkpoint (funcall (world-snapshot w)))
         (baseline (compute-restarts)) (before nil) (changed nil)
         (preview (and (eq (getf action :action) :execute) (getf action :preview)))
         (outcome
           (catch 'abort-attempt
             (handler-case (setf before (capture-managed-state w))
               (error () (throw 'abort-attempt :state-capture-failed)))
             (let ((values (handler-bind ((error (lambda (c) (condition-loop s c baseline))))
                             (multiple-value-list (evaluate-source s (getf action :source))))))
               (let ((printed (printed-values values)))
                 (setf (session-outcome s)
                       (list :commit :evaluated :operation-id (getf (session-operation s) :id)
                             :values printed :value-count (length values)
                             :values-truncated (< (length printed) (length values)))))
               (emit s :evaluated :values (getf (session-outcome s) :values))
               (let ((results (check-predicates (session-invariants s))))
                 (emit s :invariants :results results)
                 (unless (all-pass-p results) (throw 'abort-attempt :unsafe)))
               (handler-case (setf changed (not (equalp before (capture-managed-state w))))
                 (error () (throw 'abort-attempt :state-capture-failed)))
               (setf (getf (session-outcome s) :changed) changed)
               (when preview (throw 'abort-attempt :preview))
               (when (and changed (session-store s))
                 (handler-case (publish-revision s)
                   (publication-error (c)
                     (if (publication-uncertain-p c) (error c)
                         (throw 'abort-attempt :publication-failed)))))
               :accepted))))
    (if (eq outcome :accepted)
        (progn (setf (getf (session-outcome s) :commit) :accepted
                     (getf (session-outcome s) :retained) t)
               (emit s :accepted :changed changed))
        (progn
          (funcall (world-restore w) checkpoint)
          (unless (eq outcome :preview)
            (setf (session-outcome s) (list :operation-id (getf (session-operation s) :id))))
          (setf (getf (session-outcome s) :commit) :restored
                (getf (session-outcome s) :reason) outcome
                (getf (session-outcome s) :retained) nil)
          (emit s :restored :reason outcome)))
    (finish-operation s (if (eq outcome :accepted) :accepted :restored))
    (when (eq outcome :infrastructure-failed) (error 'infrastructure-error))
    outcome))
(defun perform-rollback (s action)
  (begin-operation s action)
  (setf (session-outcome s) (rollback-revision s (getf action :revision))
        (getf (session-outcome s) :operation-id) (getf (session-operation s) :id))
  (finish-operation s (getf (session-outcome s) :commit)))
(defun worker-main (s)
  (unwind-protect
       (handler-case
           (catch 'stop-worker
             (loop
               (let* ((safety (check-predicates (session-invariants s)))
                      (goals (check-predicates (session-goals s))))
                 (emit s :checks :invariants safety :goals goals)
                 (unless (all-pass-p safety)
                   (report-state s :faulted :reason :invalid-baseline) (return))
                 (when (and (session-store s) (null (current-revision (session-store s))))
                   (capture-managed-state (session-world s))
                   (publish-revision s))
                 (when (and (not (session-interactive s)) (all-pass-p goals))
                   (report-state s :success :goals goals) (return))
                 (when (<= (session-budget s) 0)
                   (report-state s :exhausted) (return))
                 (report-state s :idle :goals goals :invariants safety
                               :goals-achieved (and (session-goals s) (all-pass-p goals)))
                 (let ((action (catch 'abort-attempt (receive-action s))))
                   (when (member action '(:cancelled :exhausted))
                     (report-state s (if (eq action :cancelled) :aborted :exhausted)) (return))
                   (case (getf action :action)
                     ((:develop :execute)
                      (let ((result (attempt s action)))
                        (when (and (consp result) (eq (first result) :rollback))
                          (perform-rollback s (list :action :rollback :revision (second result))))
                        (when (member result '(:exhausted :cancelled))
                          (report-state s (if (eq result :exhausted) :exhausted :aborted))
                          (return))))
                     (:rollback (perform-rollback s action))
                     ((:inspect :describe :operations) (inspect-action s action))
                     (:check nil)
                     (:abort (if (session-interactive s)
                                 (setf (session-outcome s) (list :commit :aborted))
                                 (progn (report-state s :aborted) (return))))
                     (otherwise (emit s :rejected :reason :invalid-action)))))))
         (error (c)
           (setf (session-status s) :faulted)
           (when (session-operation s)
             (setf (getf (session-operation s) :status) :faulted))
           ;; Fault reporting must not retry the failing persistence/observation path.
           (push (list :event :fault :condition (bounded c)) (session-events s))
           (sb-concurrency:send-message (session-outbox s)
                                       (list :status :faulted :condition (bounded c)))))
    (setf (session-closed s) t)
    (sb-thread:with-mutex ((world-ownership-lock (session-world s)))
      (setf (world-active-session (session-world s)) nil))))
(defun make-session (world &key goal goals invariants (budget 100) store recovery-history operation-history interactive)
  (unless (and (or goals interactive) (integerp budget) (>= budget 0)
               (world-package world) (world-observe world)
               (world-snapshot world) (world-restore world)
               (world-managed-state world) (world-catalogue world))
    (error 'configuration-error :message "Supply world snapshot/restore, managed-state/catalogue hooks, goals (unless interactive), and nonnegative budget"))
  (let ((s (%make-session :world world :goal goal :goals (copy-tree goals) :invariants (copy-tree invariants)
                          :budget budget :store store :recovery-history recovery-history :operations operation-history :interactive interactive)))
    (when (and store (not (and (world-export world) (world-import world))))
      (error 'configuration-error :message "Durable sessions require export and import hooks"))
    (sb-thread:with-mutex ((world-ownership-lock world))
      (when (world-active-session world) (error "World already has an owner"))
      (setf (world-active-session world) s))
    (setf (session-thread s) (sb-thread:make-thread (lambda () (worker-main s))
                                                  :name "image-agent world"))
    s))
(defun session-step (s &optional action)
  (sb-thread:with-mutex ((session-controller-lock s))
    (when action
      (when (session-closed s) (error "Session is closed"))
      (sb-concurrency:send-message (session-inbox s) action))
    (or (sb-concurrency:receive-message (session-outbox s) :timeout 30)
        (error "Worker did not reach a boundary within 30 seconds"))))
(defun close-session (s)
  (unless (session-closed s)
    (sb-concurrency:send-message (session-inbox s)
                                (list :action :cancel
                                      :generation (session-generation s)))
    (sb-thread:join-thread (session-thread s) :timeout 5 :default nil))
  (session-status s))
(defun run (s proposer)
  (unwind-protect
       (loop for view = (session-step s) then
             (session-step s
               (handler-case
                   (append (funcall proposer view) (list :generation (getf view :generation)))
                 (error () (list :action :proposal-failed :generation (getf view :generation)))))
             until (member (getf view :status) '(:success :exhausted :faulted :aborted))
             finally (return view))
    (close-session s)))
(sb-ext:lock-package :image-agent)
