(eval-when (:compile-toplevel :load-toplevel :execute) (require :sb-concurrency))
(defpackage :image-agent
  (:use :cl)
  (:export :make-world :world-package :world-observe :world-snapshot :world-restore
           :world-export :world-import :world-record-form
           :make-session :session-step :run :close-session :session-events
           :session-status :session-world :session-budget :session-store
           :recover-session :publish-revision :load-revision :list-revisions :rollback-revision :*store-boundary-hook*
           :make-reference-world :reference-table :parse-one-form :validate-form
           :make-property-check :make-openai-proposer :parse-action :parse-sse :configuration-error))
(in-package :image-agent)
(defstruct (world (:constructor make-world
                      (&key package observe snapshot restore export import
                            (record-form (constantly nil)))))
  package observe snapshot restore export import record-form active-session
  (ownership-lock (sb-thread:make-mutex :name "world owner")))
(defstruct (session (:constructor %make-session))
  world goal goals invariants budget store recovery-history interactive outcome last-view (status :starting) (events nil)
  (inbox (sb-concurrency:make-mailbox)) (outbox (sb-concurrency:make-mailbox))
  thread (controller-lock (sb-thread:make-mutex :name "session controller"))
  (generation 0) (pause-count 0) (closed nil))
(define-condition configuration-error (error)
  ((message :initarg :message :reader configuration-message))
  (:report (lambda (c s) (write-string (configuration-message c) s))))
(define-condition policy-error (error) ())
(define-condition infrastructure-error (error) ())
(defvar *handling-error* nil)
(defun bounded (value &optional (limit 4096))
  (handler-case
      (let* ((*print-level* 6) (*print-length* 30) (*print-circle* t)
             (text (princ-to-string value)))
        (subseq text 0 (min limit (length text))))
    (error () "<unprintable>")))
(defun emit (session kind &rest details)
  (let ((event (list* :event kind :generation (session-generation session) details)))
    (push event (session-events session))
    (when (and (session-store session) (fboundp 'append-journal))
      (handler-case (append-journal session event)
        (error () (error 'infrastructure-error))))))
(defun parse-one-form (source package)
  (unless (and (stringp source) (<= (length source) 16384))
    (error 'policy-error))
  (let ((*read-eval* nil) (*readtable* (copy-readtable nil)) (*package* package)
        (eof (gensym)))
    (with-input-from-string (s source)
      (let ((form (read s nil eof)))
        (when (or (eq form eof) (not (eq (read s nil eof) eof)))
          (error 'policy-error))
        form))))
(defun validate-form (form)
  ;; Conservative cooperative gate. It intentionally rejects even quoted kernel symbols.
  (let ((seen (make-hash-table :test 'eq)))
    (labels ((walk (x)
               (when (and (symbolp x)
                          (or (and (symbol-package x)
                                   (member (package-name (symbol-package x))
                                           '("IMAGE-AGENT" "IMAGE-AGENT/CLI") :test #'equal))
                              (member (symbol-name x)
                                      '("UNLOCK-PACKAGE" "WITHOUT-PACKAGE-LOCKS"
                                        "DISABLE-PACKAGE-LOCKS" "INVOKE-RESTART"
                                        "INVOKE-RESTART-INTERACTIVELY") :test #'equal)))
                 (error 'policy-error))
               (when (or (consp x) (and (vectorp x) (not (stringp x))))
                 (when (gethash x seen) (error 'policy-error))
                 (setf (gethash x seen) t)
                 (if (consp x) (progn (walk (car x)) (walk (cdr x)))
                     (map nil #'walk x)))))
      (walk form)))
  form)
(defun check-predicates (checks)
  (mapcar (lambda (entry)
            (handler-case
                (let ((result (funcall (cdr entry))))
                  (if (and (consp result) (eq (car result) :property-result))
                      (list* :name (car entry) result)
                      (list :name (car entry) :status (if result :pass :fail))))
              (error (c) (list :name (car entry) :status :error
                               :condition (bounded c))))) checks))
(defun all-pass-p (results)
  (every (lambda (r) (eq (getf r :status) :pass)) results))
(defun report-state (s status &rest details)
  (setf (session-status s) status)
  (incf (session-generation s))
  (let* ((*package* (world-package (session-world s)))
         (*print-level* 6) (*print-length* 30) (*print-circle* t)
         (observation (bounded (prin1-to-string (funcall (world-observe (session-world s)))))))
    (emit s :observation :status status :world observation)
    (setf (session-last-view s)
     (list* :status status :generation (session-generation s)
            :goal (session-goal s) :observation observation
            :recovery-history (bounded (session-recovery-history s))
            :remaining (session-budget s) :outcome (session-outcome s)
            :revision (when (session-store s) (current-revision (session-store s)))
            :history (bounded (reverse (subseq (session-events s) 0 (min 8 (length (session-events s))))) 4096)
            details))
    (sb-concurrency:send-message (session-outbox s) (session-last-view s))))
(defun receive-action (s)
  (loop
    for action = (sb-concurrency:receive-message (session-inbox s))
    do (when (eq (getf action :action) :cancel) (throw 'abort-attempt :cancelled))
       (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
       (decf (session-budget s))
       (emit s :action :proposal action)
       (if (= (or (getf action :generation) -1) (session-generation s))
           (return action)
           (progn
             (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
             (report-state s (session-status s) :rejected :stale-observation
                           :condition (getf (session-last-view s) :condition)
                           :restarts (getf (session-last-view s) :restarts)
                           :goals (getf (session-last-view s) :goals)
                           :invariants (getf (session-last-view s) :invariants))))))
(defun evaluate-source (s source)
  (let* ((w (session-world s))
         (*package* (world-package w))
         (form (validate-form (parse-one-form source *package*)))
         (*standard-output* (make-broadcast-stream))
         (*error-output* (make-broadcast-stream)))
    (multiple-value-prog1 (eval form)
      (handler-case (funcall (world-record-form w) form)
        (error () (error 'infrastructure-error))))))
(defun condition-loop (s condition baseline)
  (when (typep condition 'infrastructure-error) (throw 'abort-attempt :infrastructure-failed))
  (when (or *handling-error* (typep condition 'policy-error)
            (typep condition 'sb-ext:package-lock-violation))
    (throw 'abort-attempt :rejected))
  (let ((*handling-error* t))
    (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
    (setf (session-outcome s) (list :commit :signaled :condition (bounded condition)))
    (emit s :condition :type (string (type-of condition)) :message (bounded condition))
    (loop
      for pause = (incf (session-pause-count s))
      for restarts = (remove-if (lambda (r) (member r baseline))
                                (compute-restarts condition))
      for menu = (loop for r in restarts for i from 0
                       collect (list :id (format nil "~d/~d" pause i)
                                     :name (and (restart-name r)
                                                (string (restart-name r)))
                                     :report (bounded r)))
      do (when (<= (session-budget s) 0) (throw 'abort-attempt :exhausted))
         (report-state s :paused :condition (bounded condition) :restarts menu
                       :goals (check-predicates (session-goals s))
                       :invariants (check-predicates (session-invariants s)))
         (let ((action (receive-action s)))
           (case (getf action :action)
             (:evaluate
              (handler-bind ((error (lambda (c) (declare (ignore c))
                                       (throw 'abort-attempt :repair-failed))))
                (evaluate-source s (getf action :source))))
             (:resume
              (let ((index (position (getf action :restart-id) menu
                                     :key (lambda (x) (getf x :id)) :test #'equal)))
                (when index
                  (let ((args
                          (handler-bind ((error (lambda (c) (declare (ignore c))
                                                   (throw 'abort-attempt :repair-failed))))
                            (evaluate-source s (or (getf action :arguments) "nil")))))
                    (unless (listp args) (throw 'abort-attempt :invalid-arguments))
                    (emit s :restart :id (getf action :restart-id))
                    (apply #'invoke-restart (nth index restarts) args)))))
             (:rollback (throw 'abort-attempt (list :rollback (getf action :revision))))
             ((:inspect :check) nil)
             (:abort (throw 'abort-attempt :aborted))
             (otherwise (emit s :rejected :reason :invalid-action)))))))
(defun attempt (s action)
  (let* ((w (session-world s)) (checkpoint (funcall (world-snapshot w)))
         (baseline (compute-restarts))
         (outcome
           (catch 'abort-attempt
             (let ((value (handler-bind ((error (lambda (c) (condition-loop s c baseline))))
                            (evaluate-source s (getf action :source)))))
               (setf (session-outcome s) (list :commit :evaluated :value (bounded value)))
               (emit s :evaluated :value (bounded value))
               (let ((results (check-predicates (session-invariants s))))
                 (emit s :invariants :results results)
                 (unless (all-pass-p results) (throw 'abort-attempt :unsafe)))
               (when (session-store s)
                 (handler-case (publish-revision s)
                   (publication-error (c)
                     (if (publication-uncertain-p c) (error c)
                         (throw 'abort-attempt :publication-failed)))))
               :accepted))))
    (if (eq outcome :accepted)
        (progn (setf (getf (session-outcome s) :commit) :accepted) (emit s :accepted))
        (progn (funcall (world-restore w) checkpoint)
               (setf (session-outcome s) (list :commit :restored :reason outcome))
               (emit s :restored :reason outcome)))
    (when (eq outcome :infrastructure-failed) (error 'infrastructure-error))
    outcome))
(defun worker-main (s)
  (unwind-protect
       (handler-case
           (catch 'stop-worker
             (loop
               (let* ((safety (check-predicates (session-invariants s)))
                      (goals (check-predicates (session-goals s))))
                 (emit s :checks :invariants safety :goals goals)
                 (unless (all-pass-p safety)
                   (report-state s :faulted :reason :invalid-baseline) (return))
                 (when (and (session-store s) (null (current-revision (session-store s))))
                   (publish-revision s))
                 (when (and (not (session-interactive s)) (all-pass-p goals))
                   (report-state s :success :goals goals) (return))
                 (when (<= (session-budget s) 0)
                   (report-state s :exhausted) (return))
                 (report-state s :idle :goals goals :invariants safety
                               :goals-achieved (and (session-goals s) (all-pass-p goals)))
                 (let ((action (catch 'abort-attempt (receive-action s))))
                   (when (member action '(:cancelled :exhausted))
                     (report-state s (if (eq action :cancelled) :aborted :exhausted)) (return))
                   (case (getf action :action)
                     (:evaluate
                      (let ((result (attempt s action)))
                        (when (and (consp result) (eq (first result) :rollback))
                          (setf (session-outcome s) (rollback-revision s (second result))))
                        (when (member result '(:exhausted :cancelled))
                          (report-state s (if (eq result :exhausted) :exhausted :aborted))
                          (return))))
                     (:rollback (setf (session-outcome s) (rollback-revision s (getf action :revision))))
                     ((:inspect :check) nil)
                     (:abort (if (session-interactive s)
                                 (setf (session-outcome s) (list :commit :aborted))
                                 (progn (report-state s :aborted) (return))))
                     (otherwise (emit s :rejected :reason :invalid-action)))))))
         (error (c)
           (setf (session-status s) :faulted)
           ;; Fault reporting must not retry the failing persistence/observation path.
           (push (list :event :fault :condition (bounded c)) (session-events s))
           (sb-concurrency:send-message (session-outbox s)
                                       (list :status :faulted :condition (bounded c)))))
    (setf (session-closed s) t)
    (sb-thread:with-mutex ((world-ownership-lock (session-world s)))
      (setf (world-active-session (session-world s)) nil))))
(defun make-session (world &key goal goals invariants (budget 100) store recovery-history interactive)
  (unless (and (or goals interactive) (integerp budget) (>= budget 0)
               (world-package world) (world-observe world)
               (world-snapshot world) (world-restore world))
    (error 'configuration-error :message "Supply a world, nonempty named goals, and nonnegative budget"))
  (let ((s (%make-session :world world :goal goal :goals (copy-tree goals) :invariants (copy-tree invariants)
                          :budget budget :store store :recovery-history recovery-history :interactive interactive)))
    (when (and store (not (and (world-export world) (world-import world))))
      (error 'configuration-error :message "Durable sessions require export and import hooks"))
    (sb-thread:with-mutex ((world-ownership-lock world))
      (when (world-active-session world) (error "World already has an owner"))
      (setf (world-active-session world) s))
    (setf (session-thread s) (sb-thread:make-thread (lambda () (worker-main s))
                                                  :name "image-agent world"))
    s))
(defun session-step (s &optional action)
  (sb-thread:with-mutex ((session-controller-lock s))
    (when action
      (when (session-closed s) (error "Session is closed"))
      (sb-concurrency:send-message (session-inbox s) action))
    (or (sb-concurrency:receive-message (session-outbox s) :timeout 30)
        (error "Worker did not reach a boundary within 30 seconds"))))
(defun close-session (s)
  (unless (session-closed s)
    (sb-concurrency:send-message (session-inbox s)
                                (list :action :cancel
                                      :generation (session-generation s)))
    (sb-thread:join-thread (session-thread s) :timeout 5 :default nil))
  (session-status s))
(defun run (s proposer)
  (unwind-protect
       (loop for view = (session-step s) then
             (session-step s
               (handler-case
                   (append (funcall proposer view) (list :generation (getf view :generation)))
                 (error () (list :action :proposal-failed :generation (getf view :generation)))))
             until (member (getf view :status) '(:success :exhausted :faulted :aborted))
             finally (return view))
    (close-session s)))
(sb-ext:lock-package :image-agent)
