(in-package :image-agent)
(defun json-object (&rest pairs)
  (let ((table (make-hash-table :test 'equal)))
    (loop for (key value) on pairs by #'cddr do (setf (gethash key table) value)) table))
(defun json-text (object)
  (with-output-to-string (s) (yason:encode object s)))
(defun parse-action (text)
  (unless (and (stringp text) (<= (length text) 16384)) (error 'policy-error))
  (let* ((object (let ((yason:*parse-json-booleans-as-symbols* t)) (with-input-from-string (input text)
                    (let ((value (yason:parse input)))
                      (loop for c = (read-char input nil nil) while c
                            unless (find c '(#\Space #\Tab #\Newline #\Return))
                              do (error 'policy-error))
                      value)))) (action (and (hash-table-p object) (gethash "action" object)))
         (allowed (cond ((equal action "develop") '("action" "source"))
                        ((equal action "execute") '("action" "source" "preview"))
                        ((equal action "resume") '("action" "restart_id" "arguments"))
                        ((equal action "abort") '("action")))))
    (unless allowed (error 'policy-error))
    (maphash (lambda (key value) (declare (ignore value))
               (unless (member key allowed :test #'equal) (error 'policy-error))) object)
    (cond ((equal action "develop")
           (unless (stringp (gethash "source" object)) (error 'policy-error))
           (list :action :develop :source (gethash "source" object)))
          ((equal action "execute")
           (unless (and (stringp (gethash "source" object))
                        (nth-value 1 (gethash "preview" object))
                        (member (gethash "preview" object) '(yason:true yason:false)))
             (error 'policy-error))
           (list :action :execute :source (gethash "source" object)
                 :preview (not (null (member (gethash "preview" object) '(yason:true))))))
          ((equal action "resume")
           (unless (and (stringp (gethash "restart_id" object))
                        (stringp (gethash "arguments" object))) (error 'policy-error))
           (list :action :resume :restart-id (gethash "restart_id" object)
                 :arguments (gethash "arguments" object)))
          (t (list :action :abort)))))
(defun parse-sse (text)
  "Parse complete SSE text. Network chunk boundaries are handled by the input stream."
  (when (> (length text) 1048576) (error 'policy-error))
  (let ((completed nil) (request-id nil) (output (make-string-output-stream)) (data nil))
    (labels ((dispatch ()
               (when data
                 (let* ((payload (format nil "~{~a~^~%~}" (nreverse data)))
                        (event (yason:parse payload)) (type (gethash "type" event)))
                   (when completed (error 'policy-error))
                   (cond ((equal type "response.created")
                          (setf request-id (gethash "id" (gethash "response" event))))
                         ((equal type "response.output_text.delta")
                          (write-string (gethash "delta" event) output))
                         ((equal type "response.completed")
                          (unless (equal (gethash "status" (gethash "response" event)) "completed")
                            (error 'policy-error))
                          (setf completed t))
                         ((member type '("error" "response.failed" "response.incomplete"
                                         "response.refusal.delta" "response.refusal.done") :test #'equal)
                          (error 'policy-error))))
                 (setf data nil))))
      (with-input-from-string (s text)
        (loop for raw = (read-line s nil nil) while raw
              for line = (string-right-trim '(#\Return) raw)
              do (cond ((zerop (length line)) (dispatch))
                       ((and (>= (length line) 5) (string= line "data:" :end1 5))
                        (push (string-left-trim '(#\Space) (subseq line 5)) data)))))
      (when data (error 'policy-error)))
    (unless completed (error 'policy-error))
    (append (parse-action (get-output-stream-string output))
            (when request-id (list :request-id request-id)))))
(defun environment (name) (sb-ext:posix-getenv name))
(defun api-key ()
  (or (environment "OPENAI_API_KEY")
      (let ((file (environment "OPENAI_API_KEY_FILE")))
        (when file (with-open-file (s file) (string-trim '(#\Space #\Newline #\Return) (read-line s)))))
      (error 'configuration-error :message "Set OPENAI_API_KEY or OPENAI_API_KEY_FILE")))
(defun read-response-stream (stream)
  (if (subtypep (stream-element-type stream) 'character)
      (let ((buffer (make-string-output-stream)) (count 0))
        (loop for c = (read-char stream nil nil) while c do
          (when (> (incf count) 1048576) (error 'policy-error))
          (write-char c buffer))
        (get-output-stream-string buffer))
      (let ((bytes (make-array 0 :element-type '(unsigned-byte 8)
                                :adjustable t :fill-pointer 0)))
        (loop for byte = (read-byte stream nil nil) while byte do
          (when (>= (length bytes) 1048576) (error 'policy-error))
          (vector-push-extend byte bytes))
        (babel:octets-to-string bytes :encoding :utf-8))))
(define-condition responses-error (configuration-error)
  ((kind :initarg :kind :reader responses-error-kind))
  (:default-initargs :message "Responses request failed; credentials and response body suppressed"))
(defun response-error-kind (status body)
  "Keep only a fixed classification, never provider text, headers, or credentials."
  (let ((code (ignore-errors
                (when (and (stringp body) (<= (length body) 65536))
                  (let ((value (yason:parse body)))
                    (gethash "code" (gethash "error" value)))))))
    (cond ((and (= status 400) (equal code "context_length_exceeded")) :context-overflow)
          ((or (member status '(404 405 501))
               (and (= status 400) (member code '("unsupported_model" "model_not_supported"
                  "unsupported_endpoint" "not_supported") :test #'equal))) :unsupported)
          (t :failed))))
(defun guarded-transport (request)
  (handler-case (funcall request)
    (responses-error (c) (error c))
    (sb-ext:timeout () (error 'configuration-error :message "Responses transport timed out; credentials and response body suppressed"))
    (error () (error 'configuration-error :message "Responses transport failed; credentials and response body suppressed"))))
(defun default-transport (url key body)
  (guarded-transport
    (lambda ()
      (sb-ext:with-timeout 60
        (handler-case
          (multiple-value-bind (stream status)
            (dexador:post url :headers (list (cons "Authorization" (concatenate 'string "Bearer " key))
                                            (cons "Content-Type" "application/json"))
                             :content body :want-stream t :connect-timeout 10 :read-timeout 30)
          (unwind-protect
               (progn (unless (= status 200) (error 'policy-error))
                      (read-response-stream stream))
            (close stream)))
          (dexador.error:http-request-failed (c)
            (let ((response-body (dexador.error:response-body c)))
              (unwind-protect
                   (error 'responses-error :kind
                          (response-error-kind (dexador.error:response-status c)
                            (if (streamp response-body)
                                (ignore-errors (read-response-stream response-body)) response-body)))
                (when (streamp response-body) (ignore-errors (close response-body)))))))))))
(defun make-openai-proposer (&key (transport #'default-transport)
                                 (model (environment "OPENAI_MODEL"))
                                 (base-url (or (environment "OPENAI_BASE_URL") "https://api.openai.com/v1"))
                                 (key (api-key)))
  (unless (and model (plusp (length model)) key (plusp (length key)))
    (error 'configuration-error :message "Set OPENAI_MODEL and API credentials"))
  (lambda (observation)
    (let ((body (json-text
                 (json-object "model" model "stream" t
                   "input" (vector (json-object "role" "user" "content"
                     (vector (json-object "type" "input_text" "text"
                       (format nil "You operate a live Common Lisp image. Return ONLY one JSON object: {\"action\":\"develop\",\"source\":\"one Lisp form\"}, {\"action\":\"execute\",\"source\":\"one Lisp expression\",\"preview\":false}, {\"action\":\"resume\",\"restart_id\":\"published ID\",\"arguments\":\"Lisp expression returning a list\"}, or {\"action\":\"abort\"}. Observe before editing. Do not refer to IMAGE-AGENT symbols. World context: ~a" (bounded observation 12000))))))))))
      (append (parse-sse (funcall transport
                         (concatenate 'string (string-right-trim "/" base-url) "/responses") key body))
              (list :model model)))))
