(in-package :image-agent)
(defvar *reference-tables* (make-hash-table :test 'eq))
(defun reference-table (world) (gethash world *reference-tables*))
(defun make-reference-world (&key (package-name (format nil "WORLD-~a" (gensym))) initial)
  "Reference adapter: one EQ table of readable values and direct DEFUN definitions.
It does not cover methods, classes, files, threads, indirect definitions, or foreign effects."
  (let* ((package (or (find-package package-name)
                      (make-package package-name :use '(:cl))))
         (table (make-hash-table :test 'equal))
         (sources nil)
         (symbol (intern "*STATE*" package)))
    (eval (list 'defvar symbol))
    (setf (symbol-value symbol) table)
    (dolist (pair initial) (setf (gethash (car pair) table) (cdr pair)))
    (labels ((data ()
               (sort (loop for k being the hash-keys of table using (hash-value v)
                           collect (cons k (copy-tree v))) #'string< :key #'prin1-to-string))
             (restore-data (pairs)
               (clrhash table)
               (dolist (p pairs) (setf (gethash (car p) table) (copy-tree (cdr p))))
               (setf (symbol-value symbol) table))
             (record (form)
               (when (consp form)
                 (cond ((eq (car form) 'defun)
                        (setf sources (acons (second form) (copy-tree form)
                                             (remove (second form) sources :key #'car))))
                       ((eq (car form) 'progn) (mapc #'record (cdr form))))))
             (snapshot ()
               (list (data) (copy-tree sources)
                     (loop for sym being the symbols of package
                           when (and (eq (symbol-package sym) package) (fboundp sym))
                           collect (cons sym (symbol-function sym)))))
             (restore (snap)
               (do-symbols (sym package)
                 (when (and (eq (symbol-package sym) package) (fboundp sym)
                            (not (assoc sym (third snap)))) (fmakunbound sym)))
               (restore-data (first snap))
               (setf sources (copy-tree (second snap)))
               (dolist (p (third snap)) (setf (symbol-function (car p)) (cdr p))))
             (export-state (dir)
               (let ((*package* package))
                 (write-durable (merge-pathnames "world.sexp" dir)
                                (list :data (data)
                                      :definitions (mapcar (lambda (p) (prin1-to-string (cdr p)))
                                                           (reverse sources))))))
             (import-state (dir)
               (let ((state (read-record (merge-pathnames "world.sexp" dir))))
                 (dolist (p sources) (fmakunbound (car p)))
                 (setf sources nil)
                 (restore-data (getf state :data))
                 (dolist (source (getf state :definitions))
                   (let ((*package* package)
                         (form (validate-form (parse-one-form source package))))
                     (unless (eq (car form) 'defun) (error 'policy-error))
                     (eval form) (record form)))))
             (observe () (list :data (data) :definitions (mapcar #'cdr sources))))
      (let ((world (make-world :package package :observe #'observe :snapshot #'snapshot
                               :restore #'restore :export #'export-state :import #'import-state
                               :record-form #'record)))
        (setf (gethash world *reference-tables*) table)
        world))))
