(in-package :image-agent)
(defvar *reference-tables* (make-hash-table :test 'eq))
(defun reference-table (world) (gethash world *reference-tables*))
(defun make-reference-world (&key (package-name (format nil "WORLD-~a" (gensym))) initial)
  "Reference adapter: one EQUAL table of readable values and direct DEFUN/FMAKUNBOUND edits.
It does not cover methods, classes, files, threads, indirect definitions, or foreign effects."
  (let* ((package (or (find-package package-name)
                      (make-package package-name :use '(:cl))))
         (table (make-hash-table :test 'equal))
         (sources nil) (recorded-functions (make-hash-table :test 'eq))
         (symbol (intern "*STATE*" package)))
    (eval (list 'defvar symbol))
    (setf (symbol-value symbol) table)
    (dolist (pair initial) (setf (gethash (car pair) table) (cdr pair)))
    (labels ((data ()
               (sort (loop for k being the hash-keys of table using (hash-value v)
                           collect (cons (copy-managed-value k) (copy-managed-value v))) #'string< :key #'prin1-to-string))
             (restore-data (pairs)
               (clrhash table)
               (dolist (p pairs) (setf (gethash (car p) table) (copy-managed-value (cdr p))))
               (setf (symbol-value symbol) table))
             (local-name-p (name)
               (and (symbolp name) (eq (symbol-package name) package)))
             (removal-name (form)
               (unless (and (listp form) (= (length form) 2)
                            (consp (second form)) (eq (car (second form)) 'quote)
                            (= (length (second form)) 2) (local-name-p (second (second form))))
                 (error 'policy-error))
               (second (second form)))
             (validate-edit (form)
               ;; Only direct edits (possibly inside PROGN) have recordable provenance.
               ;; Conservatively reject other references to FMAKUNBOUND, including FUNCALL.
               (labels ((scan (x)
                          (when (eq x 'fmakunbound) (error 'policy-error))
                          (cond ((consp x) (scan (car x)) (scan (cdr x)))
                                ((and (vectorp x) (not (stringp x))) (map nil #'scan x))))
                        (edit (x)
                          (cond ((and (consp x) (eq (car x) 'progn)) (mapc #'edit (cdr x)))
                                ((and (consp x) (eq (car x) 'fmakunbound)) (removal-name x))
                                ((and (consp x) (eq (car x) 'defun))
                                 (unless (local-name-p (second x)) (error 'policy-error))
                                 (scan (cddr x)))
                                (t (scan x)))))
                 (edit form)))
             (record (form)
               (validate-edit form)
               (let ((edits nil))
                 (labels ((collect-edit (x)
                            (when (consp x)
                              (cond ((eq (car x) 'progn) (mapc #'collect-edit (cdr x)))
                                    ((member (car x) '(defun fmakunbound))
                                     (let ((name (if (eq (car x) 'defun) (second x) (removal-name x))))
                                       (setf edits (acons name x (remove name edits :key #'car)))))))))
                   (collect-edit form))
                 ;; Evaluation already finished: only the final edit for each name matters.
                 (dolist (edit edits)
                   (let ((name (car edit)) (source (cdr edit)))
                     (if (eq (car source) 'fmakunbound)
                         (progn
                           (when (fboundp name) (error "Removal did not leave the function unbound"))
                           (setf sources (remove name sources :key #'car))
                           (remhash name recorded-functions)
                           (setf (documentation name 'function) nil))
                         (progn
                           (setf (gethash name recorded-functions) (symbol-function name))
                           (setf sources (acons name (copy-tree source) (remove name sources :key #'car)))))))))
             (ordered-sources () (sort (copy-list sources) #'string< :key (lambda (p) (symbol-name (car p)))))
             (managed-state ()
               (unless (eq (symbol-value symbol) table) (error "Unrecorded state binding change"))
               ;; Reject unrecorded definitions rather than silently losing them on recovery.
               (do-symbols (sym package)
                 (when (and (eq (symbol-package sym) package) (fboundp sym))
                   (unless (and (assoc sym sources) (eq (symbol-function sym) (gethash sym recorded-functions)))
                     (error "Unrecorded function change; use a direct named DEFUN"))))
               (dolist (p sources) (unless (fboundp (car p)) (error "Unrecorded function removal")))
               (list :data (data) :definitions (mapcar (lambda (p) (copy-tree (cdr p))) (ordered-sources))))
             (catalogue ()
               (mapcar (lambda (p)
                         (let* ((form (cdr p)) (body (cdddr form)))
                           (list :name (symbol-name (car p)) :arguments (copy-tree (third form))
                                 :documentation (and (stringp (first body)) (copy-seq (first body)))
                                 :source (let ((*package* package) (*print-readably* t)) (prin1-to-string form)))))
                       (ordered-sources)))
             (snapshot ()
               (list (data) (copy-tree sources)
                     (loop for sym being the symbols of package
                           when (and (eq (symbol-package sym) package) (fboundp sym))
                           collect (cons sym (symbol-function sym)))))
             (restore (snap)
               (do-symbols (sym package)
                 (when (and (eq (symbol-package sym) package) (fboundp sym)
                            (not (assoc sym (third snap))))
                   (fmakunbound sym) (setf (documentation sym 'function) nil)))
               (restore-data (first snap))
               (setf sources (copy-tree (second snap)))
               (clrhash recorded-functions)
               (dolist (p (third snap))
                 (setf (symbol-function (car p)) (cdr p) (gethash (car p) recorded-functions) (cdr p)))
               (dolist (p sources)
                 (setf (documentation (car p) 'function)
                       (and (stringp (fourth (cdr p))) (fourth (cdr p))))))
             (export-state (dir)
               (let ((*package* package))
                 (write-durable (merge-pathnames "world.sexp" dir)
                                (list :data (data)
                                      :definitions (mapcar (lambda (p) (prin1-to-string (cdr p)))
                                                           (ordered-sources))))))
             (import-state (dir)
               (let* ((*package* package) (state (read-record (merge-pathnames "world.sexp" dir))))
                 (dolist (p sources)
                   (fmakunbound (car p)) (setf (documentation (car p) 'function) nil))
                 (setf sources nil) (clrhash recorded-functions)
                 (restore-data (getf state :data))
                 (dolist (source (getf state :definitions))
                   (let ((*package* package)
                         (form (validate-form (parse-one-form source package))))
                     (unless (eq (car form) 'defun) (error 'policy-error))
                     (validate-edit form) (eval form) (record form)))))
             (observe () (list :bindings (list (list :name (symbol-name symbol) :type :hash-table :test :equal))
                               :data (data) :definitions (mapcar #'cdr sources))))
      (let ((world (make-world :package package :observe #'observe :snapshot #'snapshot
                               :restore #'restore :managed-state #'managed-state :catalogue #'catalogue :export #'export-state :import #'import-state
                               :validate-form #'validate-edit :record-form #'record)))
        (setf (gethash world *reference-tables*) table)
        world))))
