(eval-when (:compile-toplevel :load-toplevel :execute) (require :sb-posix))
(in-package :image-agent)
(defvar *store-boundary-hook* (constantly nil))
(defvar *revision-counter* 0)
(define-condition publication-error (error)
  ((uncertain :initarg :uncertain :reader publication-uncertain-p)))
(defun append-journal (session event)
  (let ((file (merge-pathnames "events.sexp" (directory-path (session-store session)))))
    (ensure-directories-exist file)
    (with-open-file (stream file :direction :output :if-exists :append :if-does-not-exist :create
                                :external-format :utf-8)
      (let ((*print-readably* t) (*print-circle* t)) (write event :stream stream))
      (terpri stream) (finish-output stream)
      (sb-posix:fsync (sb-sys:fd-stream-fd stream)))))
(defun journal-history (store)
  ;; A torn final diagnostic record is ignored; CURRENT remains authoritative.
  (let ((file (merge-pathnames "events.sexp" (directory-path store))) (events nil) (torn nil))
    (when (probe-file file)
      (with-open-file (stream file :external-format :utf-8)
        (let ((*read-eval* nil) (eof (gensym)))
          (loop for event = (handler-case (read stream nil eof) (error () (setf torn t) eof))
                until (eq event eof) do (push event events)))))
    (values (nreverse events) torn)))
(defun directory-path (path)
  (pathname (concatenate 'string (string-right-trim "/" (namestring (pathname path))) "/")))
(defun boundary (name) (funcall *store-boundary-hook* name))
(defun sync-directory (dir)
  (let ((fd (sb-posix:open (namestring dir) sb-posix:o-rdonly)))
    (unwind-protect (sb-posix:fsync fd) (sb-posix:close fd))))
(defun sync-tree (directory)
  (dolist (file (uiop:directory-files directory))
    (with-open-file (stream file :direction :input :element-type '(unsigned-byte 8))
      (sb-posix:fsync (sb-sys:fd-stream-fd stream))))
  (dolist (child (uiop:subdirectories directory)) (sync-tree child))
  (sync-directory directory))
(defun write-durable (path object)
  (with-open-file (s path :direction :output :if-exists :error :external-format :utf-8)
    (let ((*print-readably* t) (*print-circle* t)) (write object :stream s))
    (terpri s) (finish-output s) (sb-posix:fsync (sb-sys:fd-stream-fd s))))
(defun read-record (path)
  (with-open-file (s path :external-format :utf-8)
    (let ((*read-eval* nil) (*readtable* (copy-readtable nil)))
      (read s))))
(defun current-revision (store)
  (let ((path (merge-pathnames "CURRENT" (directory-path store))))
    (when (probe-file path) (read-record path))))
(defun publish-revision (session &key rollback-source)
  (let* ((root (directory-path (session-store session)))
         (id (format nil "revision-~d-~d-~d" (get-universal-time) (sb-posix:getpid) (incf *revision-counter*)))
         (dir (merge-pathnames (concatenate 'string id "/") root))
         (temporary (merge-pathnames (format nil ".CURRENT-~a" id) root))
         (uncertain nil))
    (handler-case
        (progn
          (ensure-directories-exist dir)
          (boundary :before-export)
          (funcall (world-export (session-world session)) dir)
          (boundary :after-export)
          (write-durable (merge-pathnames "manifest.sexp" dir)
                         (list :version 1 :id id :parent (current-revision root)
                               :sequence (1+ (length (list-revisions root))) :rollback-source rollback-source
                               :sbcl (lisp-implementation-version)
                               :events (reverse (copy-list (session-events session)))))
          (sync-tree dir)
          (sync-directory root)
          (boundary :artifacts-flushed)
          (write-durable temporary id)
          (boundary :before-pointer)
          (setf uncertain t)
          (sb-posix:rename (namestring temporary) (namestring (merge-pathnames "CURRENT" root)))
          (boundary :pointer-renamed)
          (sync-directory root)
          (boundary :published)
          (emit session :published :revision id)
          id)
      (error () (error 'publication-error :uncertain uncertain)))))
(defun load-revision (world store &optional (id (current-revision store)))
  (let* ((root (directory-path store)))
    (unless (and (stringp id) (plusp (length id)) (not (find #\/ id)) (not (search ".." id)))
      (error 'configuration-error :message "No valid CURRENT revision"))
    (let* ((dir (merge-pathnames (concatenate 'string id "/") root))
           (manifest (read-record (merge-pathnames "manifest.sexp" dir))))
      (unless (and (eql (getf manifest :version) 1) (equal (getf manifest :id) id)
                   (equal (getf manifest :sbcl) (lisp-implementation-version)))
        (error 'configuration-error :message "Revision identity/version mismatch"))
      (funcall (world-import world) dir))
    id))
(defun recover-session (world store &rest options)
  (load-revision world store)
  (multiple-value-bind (history torn) (journal-history store)
    (when torn
      ;; Retain the torn journal as evidence; do not append new records into its partial form.
      (let* ((root (directory-path store))
             (archive (merge-pathnames (format nil "events-torn-~d-~d.sexp"
                                                (get-universal-time) (incf *revision-counter*)) root)))
        (sb-posix:rename (namestring (merge-pathnames "events.sexp" root)) (namestring archive))
        (sync-directory root)))
    (apply #'make-session world :store store :recovery-history (last history 8) options)))

(defun list-revisions (store)
  "Newest first; only the accepted CURRENT ancestry, never orphan artifacts."
  (let ((id (current-revision store)) (seen (make-hash-table :test 'equal)) (records nil))
    (loop while id do
      (unless (and (stringp id) (plusp (length id))
                   (not (find #\/ id)) (not (search ".." id)) (not (gethash id seen)))
        (error 'configuration-error :message "Invalid revision ancestry"))
      (setf (gethash id seen) t)
      (let ((record (read-record (merge-pathnames
                                  (format nil "~a/manifest.sexp" id) (directory-path store)))))
        (unless (and (eql (getf record :version) 1) (equal (getf record :id) id))
          (error 'configuration-error :message "Invalid revision manifest"))
        (push (list :id id :sequence (getf record :sequence) :parent (getf record :parent)
                    :rollback-source (getf record :rollback-source)) records)
        (setf id (getf record :parent))))
    (loop for record in records for n from 1 do
      (if (getf record :sequence)
          (unless (eql n (getf record :sequence))
            (error 'configuration-error :message "Invalid revision sequence"))
          (setf (getf record :sequence) n)))
    (nreverse records)))
(defun resolve-revision (store target)
  (let* ((history (list-revisions store))
         (record (cond ((equal target "previous") (second history))
                       ((integerp target) (find target history :key (lambda (r) (getf r :sequence))))
                       ((stringp target)
                        (or (find target history :key (lambda (r) (getf r :id)) :test #'equal)
                            (let ((number (ignore-errors (parse-integer target))))
                              (and number (find number history :key (lambda (r) (getf r :sequence))))))))))
    (or (getf record :id)
        (error 'configuration-error :message "Select an accepted revision ID, number, or previous"))))
(defun rollback-revision (session target)
  "Worker-only transaction; callers submit :ROLLBACK through SESSION-STEP."
  (unless (eq sb-thread:*current-thread* (session-thread session))
    (error "Submit rollback through SESSION-STEP on the owning worker"))
  (let* ((world (session-world session)) (checkpoint (funcall (world-snapshot world)))
         (store (session-store session)) (target-id nil))
    (handler-case
        (progn
          (unless store (error 'configuration-error :message "Rollback requires a durable store"))
          (setf target-id (resolve-revision store target))
          (load-revision world store target-id)
          (unless (all-pass-p (check-predicates (session-invariants session)))
            (error 'configuration-error :message "Restored revision fails current safety checks"))
          (let ((id (publish-revision session :rollback-source target-id)))
            (emit session :rollback :source target-id :revision id)
            (list :commit :rolled-back :source target-id :revision id)))
      (publication-error (c)
        (if (publication-uncertain-p c) (error c)
            (progn (funcall (world-restore world) checkpoint)
                   (emit session :restored :reason :publication-failed)
                   (list :commit :restored :reason :publication-failed))))
      (error ()
        (funcall (world-restore world) checkpoint)
        (emit session :restored :reason :rollback-failed)
        (list :commit :restored :reason :rollback-failed)))))
