(defpackage :image-agent/terminal (:use :cl) (:export :main :probe-submission))
(in-package :image-agent/terminal)
(defun probe-submission (text mode package)
  "Reader-only syntax classification: no evaluator or worker action is invoked."
  (unless (and (stringp text) (<= (length text) 16384)) (return-from probe-submission "invalid"))
  (let* ((trimmed (string-left-trim '(#\Space #\Tab #\Return #\Newline) text))
         (split (position-if (lambda (c) (find c '(#\Space #\Tab #\Return #\Newline))) trimmed))
         (command (and (plusp (length trimmed)) (char= (char trimmed 0) #\/) (subseq trimmed 0 split)))
         (form (cond ((member command '("/develop" "/execute" "/preview") :test #'equal)
                      (if split (subseq trimmed split) ""))
                     (command nil)
                     ((equal mode "lisp") text))))
    (if (not form) "complete"
        (handler-case (progn (image-agent:parse-one-form form package) "complete")
          (end-of-file () "incomplete")
          (error () "invalid")))))
(defun main (arguments)
  (let ((protocol-output *standard-output*) (protocol-input *standard-input*) (workspace nil)
        (*standard-output* *error-output*) (*trace-output* *error-output*))
    (labels ((send (kind data)
               (write-line (image-agent/cli::json (image-agent/cli::object "type" (string-downcase (string kind)) "data" data)) protocol-output)
               (finish-output protocol-output))
             (read-input (mode continuation initial package)
               (send :input (image-agent/cli::object "mode" mode "continuation" (if continuation 'yason:true 'yason:false)
                                                   "initial" initial))
               (loop for line = (read-line protocol-input nil nil) do
                 (unless line (return nil))
                 (let* ((request (image-agent/cli::parse-json line)) (kind (gethash "type" request)))
                   (cond ((equal kind "probe")
                          (send :probe (image-agent/cli::object "id" (gethash "id" request)
                                       "status" (probe-submission (gethash "text" request) mode package))))
                         ((equal kind "submit")
                          (let ((text (gethash "text" request)))
                            (unless (and (stringp text) (<= (length text) 16384)) (error "Invalid terminal submission"))
                            (return text)))
                         ((equal kind "eof") (return nil))
                         (t (error "Invalid terminal request")))))))
      (handler-case
          (image-agent/cli:main arguments :submission-reader #'read-input
            :presenter (lambda (kind data)
                         (when (eq kind :startup) (setf workspace (gethash "workspace" data)))
                         (when (eq kind :view)
                           (let* ((view (gethash "view" data)) (id (gethash "revision" view))
                                  (history (and workspace (ignore-errors (image-agent:list-revisions workspace)))))
                             (setf (gethash "revision_number" view)
                                   (getf (find id history :test #'equal :key (lambda (r) (getf r :id))) :sequence))))
                         (send kind data)))
        (error () (send :error (image-agent/cli::object "text" "REPL backend failed. Check the workspace, program, and configuration; accepted revisions remain recoverable."))
                  (sb-ext:exit :code 2))))))
(sb-ext:lock-package :image-agent/terminal)
