(defpackage :image-agent/cli
  (:use :cl)
  (:export :make-tool :tool-definitions :dispatch-tool :make-controller :controller-view
           :controller-session :controller-tools :make-chat :chat-turn :chat-model :main))
(in-package :image-agent/cli)
(defun object (&rest pairs) (apply #'image-agent::json-object pairs))
(defun json (value) (image-agent::json-text value))
(defun parse-json (text)
  (unless (and (stringp text) (<= (length text) 65536)) (error "Invalid JSON size"))
  (let ((yason:*parse-json-booleans-as-symbols* t) (yason:*parse-json-arrays-as-vectors* t))
    (with-input-from-string (s text)
      (let ((value (yason:parse s)))
        (loop for c = (read-char s nil nil) while c
              unless (find c '(#\Space #\Tab #\Return #\Newline)) do (error "Trailing JSON"))
        value))))
(defstruct tool name description schema handler)
(defun schema (&rest fields)
  (let ((properties (make-hash-table :test 'equal)))
    (loop for (name type) on fields by #'cddr do
      (setf (gethash name properties) (object "type" type)))
    (object "type" "object" "properties" properties "additionalProperties" 'yason:false
            "required" (coerce (loop for (name type) on fields by #'cddr
                                     collect name) 'vector))))
(defun matches-schema-p (value schema)
  (and (let ((type (gethash "type" schema)))
         (cond ((equal type "object")
                (and (hash-table-p value)
                     (every (lambda (key) (nth-value 1 (gethash key value)))
                            (gethash "required" schema))
                     (loop for key being the hash-keys of value using (hash-value item)
                           always (let ((child (gethash key (gethash "properties" schema))))
                                    (and child (matches-schema-p item child))))))
               ((equal type "string") (stringp value))
               ((equal type "integer") (integerp value))
               ((equal type "number") (numberp value))
               ((equal type "boolean") (member value '(yason:true yason:false)))
               ((equal type "array") (and (vectorp value) (not (stringp value))
                                          (every (lambda (v) (matches-schema-p v (gethash "items" schema))) value)))
               ((equal type "null") (null value))
               (t nil)))
       (or (not (gethash "enum" schema)) (find value (gethash "enum" schema) :test #'equal))))
(defun tool-definitions (tools)
  (coerce (mapcar (lambda (tool)
                   (object "type" "function" "name" (tool-name tool)
                           "description" (tool-description tool) "parameters" (tool-schema tool)
                           "strict" 'yason:true)) tools) 'vector))
(defun dispatch-tool (tools name arguments)
  (let ((tool (find name tools :key #'tool-name :test #'equal)))
    (unless (and tool (matches-schema-p arguments (tool-schema tool)))
      (error "Unknown tool or invalid arguments"))
    (funcall (tool-handler tool) arguments)))
(defstruct (controller (:constructor %make-controller)) session view tools)
(defun terminal-p (view) (member (getf view :status) '(:faulted :exhausted :aborted :success)))
(defun view-json (view)
  ;; Plists contain Lisp world observations. Keep them bounded but give tokens typed fields.
  (object "status" (string-downcase (symbol-name (getf view :status)))
          "generation" (or (getf view :generation) 0) "revision" (getf view :revision)
          "remaining" (or (getf view :remaining) 0)
          "world" (or (getf view :observation) "")
          "outcome" (image-agent::bounded (getf view :outcome))
          "goals" (image-agent::bounded (getf view :goals))
          "invariants" (image-agent::bounded (getf view :invariants))
          "rejected" (image-agent::bounded (getf view :rejected))
          "condition" (getf view :condition)
          "restarts" (coerce (mapcar (lambda (r)
                                        (object "id" (getf r :id) "name" (getf r :name)
                                                "report" (getf r :report))) (getf view :restarts)) 'vector)))
(defun controller-action (controller arguments action &rest fields)
  (when (terminal-p (controller-view controller)) (error "Worker is terminal; restart CLI to recover"))
  (setf (controller-view controller)
        (image-agent:session-step (controller-session controller)
          (append (list :action action :generation (gethash "generation" arguments)) fields)))
  (view-json (controller-view controller)))
(defun history-json (controller)
  (let ((store (image-agent:session-store (controller-session controller))))
    (coerce (mapcar (lambda (r) (object "id" (getf r :id) "number" (getf r :sequence)
                                      "parent" (getf r :parent) "rollback_source" (getf r :rollback-source)))
                   (and store (image-agent:list-revisions store))) 'vector)))
(defun make-controller (session)
  (let ((c (%make-controller :session session :view (image-agent:session-step session))))
    (labels ((register (name description schema handler)
               (make-tool :name name :description description :schema schema :handler handler))
             (action (name description fields keyword mapper)
               (register name description (apply #'schema (append fields '("generation" "integer")))
                 (lambda (args) (apply #'controller-action c args keyword (funcall mapper args))))))
      (setf (controller-tools c)
            (list
             (register "observe_world" "Inspect current world, generation, accepted revision, goals, and live restart IDs." (schema)
                       (lambda (args) (declare (ignore args)) (view-json (controller-view c))))
             (action "evaluate_form" "Evaluate exactly one Lisp form; paused repairs remain provisional. Use the current generation." '("source" "string") :evaluate
                     (lambda (a) (list :source (gethash "source" a))))
             (action "check_world" "Run caller-owned goals and safety checks on the owning worker." nil :check (constantly nil))
             (register "list_revisions" "List accepted revisions newest first. Revision numbers are distinct from observation generations." (schema)
                       (lambda (args) (declare (ignore args)) (history-json c)))
             (action "rollback_revision" "Restore accepted revision ID, number as text, or previous. Only on explicit user rollback requests; clarify ambiguous targets. Abort any paused attempt, preserve history, and publish a NEW revision." '("revision" "string") :rollback
                     (lambda (a) (list :revision (gethash "revision" a))))
             (action "resume_restart" "Resume a live restart by opaque ID; arguments is one Lisp expression returning a list." '("restart_id" "string" "arguments" "string") :resume
                     (lambda (a) (list :restart-id (gethash "restart_id" a) :arguments (gethash "arguments" a))))
             (action "abort_attempt" "Unwind a paused attempt and restore its checkpoint; keep the interactive worker available." nil :abort (constantly nil)))))
    c))
