(defpackage :image-agent/cli
  (:use :cl)
  (:export :make-tool :tool-definitions :dispatch-tool :make-controller :controller-view
           :controller-session :controller-tools :make-chat :chat-turn :chat-model
           :compact-chat :chat-context-status :clear-chat-context :main))
(in-package :image-agent/cli)
(defun object (&rest pairs) (apply #'image-agent::json-object pairs))
(defun json (value) (image-agent::json-text value))
(defun parse-json (text &optional (limit 65536))
  (unless (and (stringp text) (<= (length text) limit)) (error "Invalid JSON size"))
  (let ((yason:*parse-json-booleans-as-symbols* t) (yason:*parse-json-arrays-as-vectors* t))
    (with-input-from-string (s text)
      (let ((value (yason:parse s)))
        (loop for c = (read-char s nil nil) while c
              unless (find c '(#\Space #\Tab #\Return #\Newline)) do (error "Trailing JSON"))
        value))))
(defstruct tool name description schema handler)
(defun schema (&rest fields)
  (let ((properties (make-hash-table :test 'equal)))
    (loop for (name type) on fields by #'cddr do
      (setf (gethash name properties) (object "type" type)))
    (object "type" "object" "properties" properties "additionalProperties" 'yason:false
            "required" (coerce (loop for (name type) on fields by #'cddr
                                     collect name) 'vector))))
(defun matches-schema-p (value schema)
  (and (let ((type (gethash "type" schema)))
         (cond ((equal type "object")
                (and (hash-table-p value)
                     (every (lambda (key) (nth-value 1 (gethash key value)))
                            (gethash "required" schema))
                     (loop for key being the hash-keys of value using (hash-value item)
                           always (let ((child (gethash key (gethash "properties" schema))))
                                    (and child (matches-schema-p item child))))))
               ((equal type "string") (stringp value))
               ((equal type "integer") (integerp value))
               ((equal type "number") (numberp value))
               ((equal type "boolean") (member value '(yason:true yason:false)))
               ((equal type "array") (and (vectorp value) (not (stringp value))
                                          (every (lambda (v) (matches-schema-p v (gethash "items" schema))) value)))
               ((equal type "null") (null value))
               (t nil)))
       (or (not (gethash "enum" schema)) (find value (gethash "enum" schema) :test #'equal))))
(defun tool-definitions (tools)
  (coerce (mapcar (lambda (tool)
                   (object "type" "function" "name" (tool-name tool)
                           "description" (tool-description tool) "parameters" (tool-schema tool)
                           "strict" 'yason:true)) tools) 'vector))
(defun dispatch-tool (tools name arguments)
  (let ((tool (find name tools :key #'tool-name :test #'equal)))
    (unless (and tool (matches-schema-p arguments (tool-schema tool)))
      (error "Unknown tool or invalid arguments"))
    (funcall (tool-handler tool) arguments)))
(defstruct (controller (:constructor %make-controller)) session view tools)
(defun terminal-p (view) (member (getf view :status) '(:faulted :exhausted :aborted :success)))
(defun printed-json (records)
  (coerce (mapcar (lambda (r) (object "text" (getf r :text)
                                     "truncated" (if (getf r :truncated) 'yason:true 'yason:false)
                                     "print_error" (if (getf r :print-error) 'yason:true 'yason:false))) records) 'vector))
(defun function-info-json (entry)
  (when entry
    (object "name" (getf entry :name) "arguments" (getf (getf entry :arguments) :text)
            "arguments_truncated" (if (getf (getf entry :arguments) :truncated) 'yason:true 'yason:false)
            "documentation" (getf entry :documentation)
            "documentation_truncated" (if (getf entry :documentation-truncated) 'yason:true 'yason:false)
            "source" (getf entry :source) "source_truncated" (if (getf entry :source-truncated) 'yason:true 'yason:false))))
(defun operation-json (entry)
  (let ((source (getf entry :source)) (outcome (getf entry :outcome)))
    (object "id" (getf entry :id) "intent" (image-agent::bounded (getf entry :intent))
            "status" (image-agent::bounded (getf entry :status))
            "preview" (if (getf entry :preview) 'yason:true 'yason:false)
            "changed" (if (getf outcome :changed) 'yason:true 'yason:false)
            "revision" (getf entry :revision) "base_revision" (getf entry :base-revision)
            "source" (and source (subseq source 0 (min 512 (length source))))
            "source_truncated" (if (and source (> (length source) 512)) 'yason:true 'yason:false))))
(defun checks-json (checks)
  (coerce (mapcar (lambda (entry) (object "name" (image-agent::bounded (getf entry :name))
                                        "status" (image-agent::bounded (getf entry :status))
                                        "condition" (getf entry :condition))) checks) 'vector))
(defun view-json (view)
  ;; Plists contain Lisp world observations. Keep them bounded but give tokens typed fields.
  (object "status" (string-downcase (symbol-name (getf view :status)))
          "generation" (or (getf view :generation) 0) "revision" (getf view :revision)
          "operation_id" (getf view :operation-id)
          "remaining" (or (getf view :remaining) 0)
          "world" (or (getf view :observation) "")
          "outcome" (image-agent::bounded (getf view :outcome))
          "result" (let ((outcome (getf view :outcome)))
                     (object "commit" (and (getf outcome :commit) (string-downcase (symbol-name (getf outcome :commit))))
                             "changed" (if (getf outcome :changed) 'yason:true 'yason:false)
                             "retained" (if (getf outcome :retained) 'yason:true 'yason:false)
                             "reason" (and (getf outcome :reason) (image-agent::bounded (getf outcome :reason)))
                             "value_count" (or (getf outcome :value-count) 0)
                             "values_truncated" (if (getf outcome :values-truncated) 'yason:true 'yason:false)
                             "values" (printed-json (getf outcome :values))
                             "next_offset" (getf outcome :next-offset)
                             "catalogue_count" (or (getf outcome :catalogue-count) 0)
                             "catalogue_truncated" (if (getf outcome :catalogue-truncated) 'yason:true 'yason:false)
                             "found" (if (getf outcome :found) 'yason:true 'yason:false)
                             "operations_truncated" (if (getf outcome :operations-truncated) 'yason:true 'yason:false)
                             "functions" (coerce (mapcar #'function-info-json (getf outcome :catalogue-infos)) 'vector)
                             "function_info" (function-info-json (getf outcome :function-info))
                             "operation_records" (coerce (mapcar #'operation-json (getf outcome :operation-records)) 'vector)
                             "catalogue" (printed-json (getf outcome :catalogue))
                             "function" (printed-json (and (getf outcome :function) (list (getf outcome :function))))
                             "operations" (printed-json (getf outcome :operations))))
          "goal_checks" (checks-json (getf view :goals))
          "safety_checks" (checks-json (getf view :invariants))
          "goals" (image-agent::bounded (getf view :goals))
          "invariants" (image-agent::bounded (getf view :invariants))
          "rejected" (image-agent::bounded (getf view :rejected))
          "condition" (getf view :condition)
          "restarts" (coerce (mapcar (lambda (r)
                                        (object "id" (getf r :id) "name" (getf r :name)
                                                "report" (getf r :report))) (getf view :restarts)) 'vector)))
(defun controller-action (controller arguments action &rest fields)
  (when (terminal-p (controller-view controller)) (error "Worker is terminal; restart CLI to recover"))
  (setf (controller-view controller)
        (image-agent:session-step (controller-session controller)
          (append (list :action action :generation (gethash "generation" arguments)) fields)))
  (view-json (controller-view controller)))
(defun history-json (controller)
  (let ((store (image-agent:session-store (controller-session controller))))
    (coerce (mapcar (lambda (r) (object "id" (getf r :id) "number" (getf r :sequence)
                                      "parent" (getf r :parent) "rollback_source" (getf r :rollback-source)))
                   (and store (image-agent:list-revisions store))) 'vector)))
(defun make-controller (session)
  (let ((c (%make-controller :session session :view (image-agent:session-step session))))
    (labels ((register (name description schema handler)
               (make-tool :name name :description description :schema schema :handler handler))
             (action (name description fields keyword mapper)
               (register name description (apply #'schema (append fields '("generation" "integer")))
                 (lambda (args) (apply #'controller-action c args keyword (funcall mapper args))))))
      (setf (controller-tools c)
            (list
             (register "inspect_world" "Inspect application state, checks, revision, and function catalogue. Start with offset=0; use result.next_offset to fetch subsequent pages. Generation is returned for future actions." (schema "offset" "integer")
                       (lambda (args)
                         (unless (>= (gethash "offset" args) 0) (error "Catalogue offset must be nonnegative"))
                         (controller-action c (object "generation" (getf (controller-view c) :generation)) :inspect :offset (gethash "offset" args))))
             (action "describe_function" "Inspect a managed function's arguments, documentation, and source." '("name" "string") :describe
                     (lambda (a) (list :name (gethash "name" a))))
             (register "list_operations" "Inspect recent operation attempts and outcomes, newest first. Does not re-execute them." (schema)
                       (lambda (args) (declare (ignore args))
                         (controller-action c (object "generation" (getf (controller-view c) :generation)) :operations)))
             (action "develop_form" "Add, redefine, or remove functionality using one Lisp form. The reference adapter supports (fmakunbound 'local-name), optionally grouped with definitions in PROGN. Removal keeps callers. Safe managed changes persist; unchanged state creates no revision. Paused repairs share the active transaction." '("source" "string") :develop
                     (lambda (a) (list :source (gethash "source" a))))
             (action "execute_form" "Execute one Lisp expression, including nested calls to existing functions. Retain safe managed changes by default; preview=true restores managed state after returning values. Preview cannot undo unmanaged external effects." '("source" "string" "preview" "boolean") :execute
                     (lambda (a) (list :source (gethash "source" a) :preview (eq (gethash "preview" a) 'yason:true))))
             (action "check_world" "Run caller-owned goals and safety checks on the owning worker." nil :check (constantly nil))
             (register "list_revisions" "List accepted revisions newest first. Revision numbers are distinct from observation generations." (schema)
                       (lambda (args) (declare (ignore args)) (history-json c)))
             (action "rollback_revision" "Restore accepted revision ID, number as text, or previous. Only on explicit user rollback requests; clarify ambiguous targets. Abort any paused attempt, preserve history, and publish a NEW revision." '("revision" "string") :rollback
                     (lambda (a) (list :revision (gethash "revision" a))))
             (action "resume_restart" "Resume a live restart by opaque ID; arguments is one Lisp expression returning a list." '("restart_id" "string" "arguments" "string") :resume
                     (lambda (a) (list :restart-id (gethash "restart_id" a) :arguments (gethash "arguments" a))))
             (action "abort_attempt" "Unwind a paused attempt and restore its checkpoint; keep the interactive worker available." nil :abort (constantly nil)))))
    c))
